### ISSUE TITLE
Compatibility with net5.0

### ISSUE THREAD

**Issue by HEBOS** [dotnet/format#1020]
Hi guys,

You are doing a great job.
Is there any timeframe for this tool to become compatible with net5.0?

Thanks

**Comment by JoeRobich** [comment]
Hi @HEBOS, Thanks for trying out dotnet-format. I use dotnet-format with NET 5 daily. Can you describe what issues you are having with dotnet-format and NET 5?

**Comment by HEBOS** [comment]
Did you try to run dotnet tool install  inside docker image on linux? It is failing.
Here is an excerpt from my Dockerfile:

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
dotnet tool install -g dotnet-format

**Comment by jmarolf** [comment]
@HEBOS what the error message that get reported in that case?

**Comment by JoeRobich** [comment]
@HEBOS If you are seeing the "bash: dotnet-format: command not found" message when trying to invoke dotnet-format, try adding the tools directory to your PATH.

This is the message that is printed when installing dotnet-format in the container.

```console
root@97bab0e262ad:/workspaces/output-test#  dotnet tool install -g dotnet-format
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: dotnet-format
Tool 'dotnet-format' (version '5.0.211103') was successfully installed.
```

**Comment by JoeRobich** [comment]
@HEBOS If the issue you are seeing is "Warnings were encountered while loading the workspace. Set the verbosity option to the 'diagnostic' level to log warnings." and the warning when invoking dotnet-format with the `-v diag` option looks like the following:

```console
/usr/share/dotnet/sdk/5.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets: (241, 5): The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder '/usr/local/share/dotnet/sdk/NuGetFallbackFolder'.
```

Running `ln -s /usr/share/dotnet /usr/local/share/dotnet` will ensure that the dotnet sdk folders are where the NuGet target expects.

**Comment by HEBOS** [comment]
I mislead you stating that I'm using mcr.microsoft.com/dotnet/sdk:5.0.
That one worked.
However, I need dotnet-format in runtime, so I need mcr.microsoft.com/dotnet/aspnet:5.0 instead.
Is there anythink, I could install on aspnet:5.0, in order to avoid using big SDK image?

**Comment by JoeRobich** [comment]
@HEBOS dotnet-format depends on the SDK providing MSBuild in order to load project and solution files. It *may* be possible to perform whitespace formating when passing the `--folder` option, but that would be considered an unsupported scenario.

**Comment by HEBOS** [comment]
@JoeRobich 
I just need whitespace formatting, nothing else.

But the problem is that when I try to install it inside mcr.microsoft.com/dotnet/aspnet:5.0 docker image, using

`dotnet tool install -g dotnet-format`

... this is what I get:

_Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download_

**Comment by JoeRobich** [comment]
@HEBOS Ah, that is a problem. It seems you will need an SDK just to install dotnet-format.

**Comment by jmarolf** [comment]
closing this as answered
