### ISSUE TITLE
Upgrade to .NET Core 2.2

### ISSUE THREAD

**Issue by francisminu** [dotnet/format#104]
This project throws an incompatible error while being added to a project with .Net Core 2.2. Is it possible to update the target framework to core 2.2 or to .net standard so that it supports all of them?

**Comment by jmarolf** [comment]
@francisminu could you post the exact steps you took to get an error? I believe global tools targeting older version of .NET Core are supposed to "Just Work" on newer runtimes

**Comment by francisminu** [comment]
Exactly, that was my understanding too. Not sure why it threw off.
Here are the steps:
1. Created a new Console Application with Target Framework = .NET Core 2.2
2. By clicking the 'Dependencies' -> Chose 'Manage Nuget Packages'
3. Searched dotnet-format and gave an install - Version: 3.0.4

Please let me know if you find something.

Thanks!

**Comment by jmarolf** [comment]
The dotnet-format nuget package is not intended to be installed into a project.  The correct way to install it is to use `dotnet tool install` from the commandline like so:

```console
dotnet tool install -g dotnet-format
```

see the [how to use](https://github.com/dotnet/format#how-to-use) section for more information
