### ISSUE TITLE
The tool creates formatDiagnosticLog.binlog in the solution directory and no way to disable this or redirect

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/format#1041]
Running `dotnet-format some.sln --verbosity diagnostic` will create a file called `formatDiagnosticLog.binlog` next to the solution file. There doesn't seem to be a way to redirect this to another directory, rename it or disable it.

We want to keep diagnostic output to be able to detect issues with the solution loading, but adding files next to the solution makes the experience pretty bad for local enlistments since git will pick it up as a new file to be added.

Ideally there would be a way to disable writing of the file from command line, or at the very least ability to specify the file path to write it to.

**Comment by JoeRobich** [comment]
@jmarolf I think it is time to add a `--binarylog <filename>` option.
