### ISSUE TITLE
InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/format#109]
I get an InvalidOperationException when I run dotnet-format in a scheduled task. It works normally when I run the same command on the command line outside of a scheduled task. 

I tried with the latest release and preview version 3.0.5-prerelease.19219.2.

Command line
```
dotnet-format --dry-run --workspace "C:\Users\User\Solution\Solution.sln"
```

Stacktrace
```
Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, String verbosity, Boolean dryRun, Boolean check, String files, IConsole console) in /_/src/Program.cs:line 79
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass3_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseExceptionHandler>b__5_0>d.MoveNext()
```

**Comment by jmarolf** [comment]
This means that the environment in which dotnet format is running in is configured such that it can't find where MSBuild is located.  How did you install `dotnet format` on the machine?

**Comment by jmarolf** [comment]
https://github.com/dotnet/format/blob/3684ac0b00c3c082a5c6e3ca753b1f0c6ab17f1d/src/Program.cs#L79-L81

**Comment by JoeRobich** [comment]
@nnpcYvIVl Has you issue been resolved or can you share any more details about your installation and how you are running dotnet-format? Thanks!

**Comment by nnpcYvIVl** [comment]
@jmarolf @JoeRobich Sorry for the delay.

MSBuild was installed with Build Tools for Visual Studio 2017 and works without issue.

I installed dotnet-format with this command
```
dotnet tool install -g dotnet-format
```

Then I copied the "%userprofile%\.dotnet\tools" folder to "%ProgramFiles(x86)%\dotnet-format".

From the command line I ran a batch file containing this command
```
"C:\Program Files (x86)\dotnet-format\dotnet-format.exe" --dry-run --workspace "C:\Users\User\ClassLibrary1\ClassLibrary1.sln" 1> "C:\Users\User\output.txt" 2>&1
```

It worked as expected and this was the output
```
Formatting code files in workspace 'C:\Users\User\ClassLibrary1\ClassLibrary1.sln'.
Formatting code files in project 'ClassLibrary1'.
Formatted code file 'Class1.cs'.
Format complete.
```

When I create a scheduled task using the same credentials and pointing to the same batch file I get the failure with the stacktrace posted above.

**Comment by JoeRobich** [comment]
@nnpcYvIVl dotnet-format uses the MSBuild from the .NET Core SDK. Does the user that the scheduled task runs as have .NET Core installed?

**Comment by nnpcYvIVl** [comment]
@JoeRobich Thanks for the clarification on the MSBuild version.

.NET Core is installed for that user, here is the output of a couple of commands:
```
dotnet --info
```
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```  
```
dotnet tool list -g
```
```
Package Id         Version      Commands     
---------------------------------------------
dotnet-format      3.0.4        dotnet-format
```

**Comment by JoeRobich** [comment]
@nnpcYvIVl Instead of moving dotnet-format out of the .dotnet/tools folder. Can you instead install dotnet-format as the user that the scheduled task runs as. I am not sure manually relocating dotnet global tools is supported.

**Comment by jeffreyelms-vr** [comment]
Not directly related, but I received the same error when trying to run from a make file under msys2 (or cygwin). Here was my solution that I still want to try to improve. Basically I needed two additional paths in my search path: the install path `%USERPROFILE%\.dotnet\tools` ([see](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)) and `C:\Program Files\dotnet`

```
DOTNET_TOOLS = $(shell cygpath $(USERPROFILE)/.dotnet/tools)

format-check:
       PATH=$(PATH):/c/Program\ Files/dotnet:$(DOTNET_TOOLS) dotnet-format --check -v diagnostic -w $(SOLUTION)
```

**Comment by elmsfu** [comment]
Not directly related, but I received the same error when trying to run from a make file under msys2 (or cygwin). Here was my solution that I still want to try to improve. Basically I needed two additional paths in my search path: the install path `%USERPROFILE%\.dotnet\tools` ([see](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)) and `C:\Program Files\dotnet`

```
DOTNET_TOOLS = $(shell cygpath $(USERPROFILE)/.dotnet/tools)

format-check:
       PATH=$(PATH):/c/Program\ Files/dotnet:$(DOTNET_TOOLS) dotnet-format --check -v diagnostic -w $(SOLUTION)
```

**Comment by jmarolf** [comment]
If we want running from a non-sdk environment to work, I would recommend allowing users to specify an explicit path to msbuild.

**Comment by JoeRobich** [comment]
dotnet-format is a dotnet tool designed to be installed and run by the dotnet CLI. We won't support other installation method at this time. dotnet CLI local tools are a newer concept that may work well for this scenario.

**Comment by Loffe** [comment]
I ran into this issue as well, probably due to another installation method. The dotnet core SDK was missing, and the error message `InvalidOperationException: Sequence contains no elements` does not really give any clue of the real error.

Can this error message be improved to say something along the lines:
`Could not find MSBuild, make sure .NET Core SDK is installed`

**Comment by JoeRobich** [comment]
@Loffe Thanks for the suggestion. It'll be in the next release.
