### ISSUE TITLE
[Feature Request] A way to set default args

### ISSUE THREAD

**Issue by BenjaBobs** [dotnet/format#1124]
I'd love it if there was a way to set default args for the `dotnet format` command.
Preferably using a file such as `.dotnetformat` or similar, such that I can commit it to my repo and ensure all developers use the same arguments across my team.

**Comment by jmarolf** [comment]
@JoeRobich response files should enable this right?

**Comment by JoeRobich** [comment]
@BenjaBobs As @jmarolf points out, we support RSP files. You can pass an RSP file when running dotnet format by typing the `@` symbol followed by the file name. 

 For instance, we use a [validate.rsp](https://github.com/dotnet/format/blob/main/validate.rsp) file as part of our CI, but we can run it locally by invoking `dotnet format @validate.rsp`

**Comment by BenjaBobs** [comment]
Note to future people who find this issue: If you're using powershell you have to escape the `@` with the grave character like this ```dotnet format `@validate.rsp```.
