### ISSUE TITLE
Issue with v5.1.225507

### ISSUE THREAD

**Issue by admiralAwkbar** [dotnet/format#1136]
Hey all!

It seems Release:
- `https://github.com/dotnet/format/releases/tag/v5.1.225507`

Has a bug that you can't run the command:
```bash
bash-5.1# dotnet-format --version
--version option cannot be combined with other arguments.
```

Any help getting that resolved would be awesome :)

**Comment by jmarolf** [comment]
@JoeRobich  I assume this is due to upgrades system.commandline?

**Comment by JoeRobich** [comment]
> @JoeRobich I assume this is due to upgrades system.commandline?

Must be. I'll look and see if there is a fix.

**Comment by admiralAwkbar** [comment]
@jmarolf @JoeRobich thanks for the work on this!
Trying to get the [GitHub Super-Linter](https://github.com/super-linter) a new release and noticed this broke the automation checks :)
Once you guys cut a release I think we're back in business
