### ISSUE TITLE
Using dotnet-format for Xamarin projects

### ISSUE THREAD

**Issue by thiemf** [dotnet/format#1178]
Hello, 

we're using dotnet-format for a .NET Standard project and it's working very nice 👍 

We're also trying to use it for a Xamarin.iOS & a Xamarin.Android project, but it's somehow not working. Is that also supported? Wasn't able to find much information unfortunately. 

For the Xamarin.iOS project I'm running (on a Mac):
`dotnet format <path to iOS csproj file> --no-restore -v diag`

...but I'm getting this error, and no files are formatted:
`Msbuild failed when processing the file '<path to iOS csproj file>' with message: The imported project "/usr/local/share/dotnet/sdk/5.0.203/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/5.0.203//Xamarin/iOS/Xamarin.iOS.CSharp.targets" is correct, and that the file exists on disk.`

It seems the error is referring to this import in the iOS csproj file:
`<Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />`

I'm guessing maybe `$(MSBuildExtensionsPath)` is set differently by dotnet-format compared to the Xamarin tooling. 

For Xamarin.Android it's a similar error. 

Any help is appreciated. 
Thank you.

Best regards,
Matthias

**Comment by JoeRobich** [comment]
@thiemf dotnet-format only supports loading newer SDK-style projects. Xamarin apps still use the older legacy project style. This will change with MAUI in NET 6, but that doesn't help your current situation.

You can work around project loading by using the `--folder` flag which will limit you to whitespace formatting only. The command would look something like this  `dotnet format <path to source code> --folder -v diag`

**Comment by thiemf** [comment]
@JoeRobich thanks, that worked 😄 

For now I'm happy with the whitespace formatting. Will check again when .NET6 is out 👍
