### ISSUE TITLE
Cannot list the version by --version

### ISSUE THREAD

**Issue by sangwoo-joh** [dotnet/format#1206]
I've installed dotnet format (sdk 3.1) via following instructions (in both Ubuntu 16.04 and Debian 10):

``` bash
apt install apt-transport-https
wget --no-check-certificate https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt update && apt install dotnet-sdk-3.1
dotnet tool install -g dotnet-format
export PATH=$PATH:~/.dotnet/tools/dotnet-format
```

After installation, when I type `dotnet format --version` or directly `~/.dotnet/tools/dotnet-format --version` then I got an error message saying:

```bash
dotnet format --version
--version option cannot be combined with other arguments.

... long help messages...
```

I'm not sure this is a version-specific issue or not. Please help me!

**Comment by sangwoo-joh** [comment]
As soon as I've installed dotnet-format, it showed:

```bash
'dotnet-format' 도구('5.1.225507' 버전)가 설치되었습니다.
```

It says the version `5.1.225507`.

**Comment by sangwoo-joh** [comment]
After doing some tests, I found that this is a version-specific issue with the latest version (5.1.225507). I've reinstalled dotnet-format with a different version (5.0.211103) and it worked fine.

**Comment by JoeRobich** [comment]
Sorry @sangwoo-joh, we fixed this issue as https://github.com/dotnet/format/issues/1136 but have not published a new build.

**Comment by sangwoo-joh** [comment]
@JoeRobich Thanks, I will wait for the update!
