### ISSUE TITLE
formatting causes SA1000

### ISSUE THREAD

**Issue by pgrm** [dotnet/format#1324]
running `dotnet format` on code containing 

```csharp
MyClass x = new (123, 'abc');
```

formats it to 

```csharp
MyClass x = new(123, 'abc');
```

(the space after `new` is missing)

However, this causes StyleCop issue SA1000

> error SA1000: The keyword 'new' should be followed by a space.

- How can I configure the script to keep the space after `new`?
- Shouldn't this be the default behaviour, or is the StyleCop rule outdated and should be fixed to include this new C# feature?

According to the examples in https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9 it seems that maybe stylecop should be rather updated.

**Comment by JoeRobich** [comment]
@pgrm There already appears to be an issue open against StyleCop.Analyzers for this issue. See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3382

Closing as this should be fixed in the StyleCop.Analyzers package.
