### ISSUE TITLE
Cant Install dotnet Format

### ISSUE THREAD

**Issue by adolfie450** [dotnet/format#1325]
Hi,

Thanks for this package, from what I understand it seems it does help a lot.

Please pardon my ignorance but I am running into an error on install. 

Visual Studio Community: 16.11.12
Dot net SDK, 5 / 6 tried them both

I am however failing on install, even if I target the Dotnet Format Package all the way back to 3.xx

I dont understand what its on about with this _supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any__

your assistance is greatly appreciated.  

  ```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
```

_Severity	Code	Description	Project	File	Line	Suppression State
Error		Package 'dotnet-format 5.1.225507' has a package type 'DotnetTool' that is not supported by project 'xxx'._	

_Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package dotnet-format 5.1.225507 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package dotnet-format 5.1.225507 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any_

**Comment by CaringDev** [comment]
It seems you are trying to install as a project dependency instead of a tool.
Did you run `dotnet tool install dotnet-format`?

**Comment by adolfie450** [comment]
Hi

Thanks, this did the trick

Thanks

G

**Comment by JoeRobich** [comment]
Closing as this appears to be resolved.
