### ISSUE TITLE
Support for .Net Core 3+

### ISSUE THREAD

**Issue by SandraMarszalek** [dotnet/format#1339]
Hi.
Is there going to be support for .Net Core 3+ anytime soon? I would love to use dotnet format again for my newest projects but for now sadly it's not possible

**Comment by JoeRobich** [comment]
Hi @SandraMarszalek, We are not aware of any issues using dotnet-format on newer versions of the SDK. Can you share some of the issues you've had using dotnet-format with .NET Core 3+?

**Comment by SandraMarszalek** [comment]
Hi
Tbh I can't install dotnet-format - while trying to install nugget package of any version it tells me that it doesn't support netcoreapp in version higher than 2.1. 
As I read it now I gave an incorrect question name - I should have been asking about netcoreapp sorry.

**Comment by SandraMarszalek** [comment]
Update on this problem - I've managed to install this after reinstalling SDK and using --version in install command. 
The tool works unless I want to specify exact file that I want to format. It ends without any error but no changes are made. I'm using "dotnet format --include myfilename". It looks for the file in correct solution but there in no effect. I've tried specified full path to the file but that doesn't work as well for me.

**Comment by JoeRobich** [comment]
> I've managed to install this after reinstalling SDK and using --version in install command.

1. Which SDK did you install?
2. What was the command you used for installing dotnet-format?

@SandraMarszalek A few more questions.

**Comment by SandraMarszalek** [comment]
I've installed SDK 6.0 and earlier 5.0. The installation command for dotnet format was (hope I remember correctly)
dotnet tool install dotnet-format --version 5.1.225507

**Comment by JoeRobich** [comment]
If you installed NET 6 Preview 7 or RC 1 then dotnet-format is part of the SDK and available without installing as a global/local tool. File paths when using `--include` are relative to the solution or project file that is being formatted. It would be helpful so see the output of running `dotnet format --include myfilename -v diag` to get more logging.
