### ISSUE TITLE
pre-commit requires preview sdk

### ISSUE THREAD

**Issue by leotsarev** [dotnet/format#1350]
Reproduce steps:
---

1. Make sure there is no net6-preview sdk installed globally
1. Use following `.pre-commit-config.yaml`
```
repos:
-   repo: https://github.com/dotnet/format
    rev: "v5.1.225507"  # Specify a tag or sha here, or run "pre-commit autoupdate"
    hooks:
    -   id: dotnet-format
```
3. Type `pre-commit run`

Expected result:
---
Everything fine

Actual result:
---
``` 
Could not execute because the application was not found or a compatible .NET SDK is not installed.
    Possible reasons for this include:
      * You intended to execute a .NET program:
          The application 'pack' does not exist.
      * You intended to execute a .NET SDK command:
          A compatible installed .NET SDK for global.json version [6.0.100-preview.1.21103.13] from [C:\Users\leo\.cache\pre-commit\repo5e5uh95j\global.json] was not found.
          Install the [6.0.100-preview.1.21103.13] .NET SDK or update [C:\Users\leo\.cache\pre-commit\repo5e5uh95j\global.json] with an installed .NET SDK:
```

**Comment by leotsarev** [comment]
I haven't found the way to pre-commit / dotnet-format to use release-version SDK. Pinning SDK in repo doesn't help

**Comment by leotsarev** [comment]
AFAIK, problem is following:
1. Pre-commit downloads tag of dotnet-format repo
2. Tries to pack/install
3. The global.json file from repo is used, requesting preview sdk.

**Comment by leotsarev** [comment]
I think that's strange mode of operation. I think pre-commit dotnet integration should have mode to use dotnet-tools.json

**Comment by JoeRobich** [comment]
Hi @leotsarev, You seem to have run into the same issue as https://github.com/dotnet/format/issues/1318. 

> I think pre-commit dotnet integration should have mode to use dotnet-tools.json

I agree. I thought it was an interesting choice to build our tool locally when running pre-commit. We welcome pull requests to make this experience better.

**Comment by leotsarev** [comment]
After investigation, another option will be just use pre-commit "local" mode to use dotnet format installed as local tool / part of sdk and skip downloading at all.

I'll update integrations.md with info about this option. PR will follow :-)
