### ISSUE TITLE
Question: Error when dotnet 6.0 and 3.1 is installed 

### ISSUE THREAD

**Issue by willsbctm** [dotnet/format#1463]
What I want:

- Even when have dotnet 6 installed - that already has dotnet format [included](dotnet-tool.json), I would like to use dotnet format with the version specified in [dotnet-tool.json](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use#restore-a-local-tool-installed-by-others)

# Environment data

``` 
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

# How to reproduce
Create a dotnet project with
- global.json
`{
  "sdk": {
    "version": "3.1",
    "rollForward": "latestPatch"
  }
}`
- dotnet-tool.json
```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-format": {
      "version": "5.1.250801",
      "commands": [
        "dotnet-format"
      ]
    }
  }
}
```

After I run at the root project folder `dotnet tool restore` and receive the message `Tool 'dotnet-format' (version '5.1.250801') was restored. Available commands: dotnet-format`

And run 
`dotnet format --version` at the same folder I receive the message `6.0.252703`

# What I expected
When I run `dotnet format --version` at the root project folder I expected receive the message `5.1.250801`

I'm not be able to exec dotnet format because there are break changes between `5.1.250801` and `6.0.252703` versions

Am I doing something wrong?

Tks.

**Comment by JoeRobich** [comment]
@willsbctm Use the following to invoke the local tool version of format:  `dotnet tool run dotnet-format {options}`.

```console
~\source\repos\roslyn> dotnet format --version
6.0.252703+68bc36719088c86b0ff01334039b0611741b8276

~\source\repos\roslyn> dotnet tool run dotnet-format --version
5.0.141503+16cdc7d5ac4ce373a93d714ff048048430bfad14
```

**Comment by willsbctm** [comment]
@JoeRobich , thank you so much! Everything works.
