### ISSUE TITLE
What is the default set of formatting/styles rules used by dotnet-format?

### ISSUE THREAD

**Issue by N0D4N** [dotnet/format#1520]
Title is pretty descriptive. Is it save to assume that [`.editorconfig`](https://github.com/dotnet/format/blob/e753815b50f727de6744774133db0214cb634871/.editorconfig) file used in `dotnet/format` repo contains same rules as running `dotnet-format` when no `.editorconfig` file is present in the solution?

**Comment by JoeRobich** [comment]
> Is it save to assume that [`.editorconfig`](https://github.com/dotnet/format/blob/e753815b50f727de6744774133db0214cb634871/.editorconfig) file used in `dotnet/format` repo contains same rules as running `dotnet-format` when no `.editorconfig` file is present in the solution?

The defaults are defined in Roslyn. You can see an example .editorconfig with all the default options at https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2022#example-editorconfig-file

**Comment by N0D4N** [comment]
I see, thanks for the answer
