### ISSUE TITLE
Error when running under .NET 6.0.200 in a container

### ISSUE THREAD

**Issue by mispencer** [dotnet/format#1521]
We are running dotnet-format in a container (mcr.microsoft.com/dotnet/sdk:6.0). As of today, that tag was upgraded to .NET 6.0.200, and dotnet format started failing with the following error: 
```
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

I creating a simple example here: https://github.com/mispencer/net6_0_200-docker-format-issue/blob/master/Dockerfile
The build-working target, referencing a direct image hash to the old 6.0.10x image, works.
The build-broken target, referencing mcr.microsoft.com/dotnet/sdk:6.0 tag and thus 6.0.200, fails with said error.

**Comment by ranma42** [comment]
might be related to https://github.com/dotnet/format/issues/1519

**Comment by Ekwy** [comment]
My team landed on the same issue.

**Comment by sungam3r** [comment]
The same here https://github.com/graphql-dotnet/server/runs/5383398523?check_suite_focus=true#step:5:315

**Comment by JoeRobich** [comment]
Closing as duplicate of https://github.com/dotnet/format/issues/1519. See this comment for a workaround https://github.com/dotnet/format/issues/1519#issuecomment-1055922333
