### ISSUE TITLE
Leave files when changes cannot be merged

### ISSUE THREAD

**Issue by madelson** [dotnet/format#1574]
When I run `dotnet-format`/`dotnet format` on large projects, some files will be left in a non-building state with a comment like:

```
/* Unmerged change from project 'ProjectName(netstandard2.0)'
Before:
...
/* existing c-style comment */
```

In my case, there is another C-style comment within the commented-out block which terminates the "outer" comment and results in invalid syntax.

If the formatter can't handle a file for whatever reason, I'd much rather it leave that file unchanged (perhaps printing an error to stdout) instead of leaving artifacts like this in it. That behavior is frustrating regardless, but especially so if it breaks the build as in the case described above.

I'm running `dotnet-format My.sln --diagnostics=IDE0161`

**Comment by JoeRobich** [comment]
@madelson I assume that a codefix is moving or removing a bit of code and that is also removing the comment terminator, but it is unclear what might be the culprit.

Is this a project you can share? or can you provide a file that demonstrates this behavior?

**Comment by madelson** [comment]
@JoeRobich after re-running the commands that were previously giving me this, I can no longer seem to reproduce it :-/. Feel free to close this for now and I will re-open if it comes up again.

**Comment by RikkiGibson** [comment]
I have seen this occasionally as well and I suspect some kind of concurrency bug is causing it.
