### ISSUE TITLE
Update `Microsoft.NETCore.Compilers` to `Microsoft.Net.Compilers.Toolset`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/format#1580]
Starting with https://github.com/dotnet/roslyn/pull/60839, no new versions are going to be pushed for `Microsoft.NETCore.Compilers` package.

The following needs to be updated:

https://github.com/dotnet/format/blob/68502482e34922e02108f6c1e7f7913bfecd1058/eng/Version.Details.xml#L4-L7

https://github.com/dotnet/format/blob/ec7537dd0645b35fc9057006639ca41e37d16348/eng/Versions.props#L20

https://github.com/dotnet/format/blob/3410eb677cc8bdfb4a738ba9f119d3612e5e2767/Directory.Packages.props#L17-L26

Otherwise, arcade will not use any new versions of these packages.

cc @JoeRobich @jaredpar

**Comment by JoeRobich** [comment]
Thanks for opening @Youssef1313! You think I would know better =)

**Comment by JoeRobich** [comment]
Change has flowed into main. Closing this issue.
