### ISSUE TITLE
dotnet format --verify-no-changes does not respect --severity arguments

### ISSUE THREAD

**Issue by mdit** [dotnet/format#1594]
Hello,

I was under the impression that specifying a `--severity` level together with the `--verify-no-changes` option would only return a non-zero exit code if any changes were identified at a severity level equal or higher than the supplied level.

This would give it the same behavior as the standard command, for example, that the following would ignore 'info' level changes:
  `dotnet format --verify-no-changes --severity warn` 

This behavior would be great for running `dotnet format` in a build pipeline where certain styling suggestions are only set to `suggestion` in an `.editorconfig` file.

I appreciate that this might be by design, but wondered if it was the intended behavior - if so is there any way to work around this behaviour?

**Comment by JoeRobich** [comment]
@mdit The expectation is that --verify-no-changes does respect the --severity option. Can you provide the console logging from your run of dotnet-format?

**Comment by mdit** [comment]
@JoeRobich thank you for coming back to me, that is what I expected should be the case.
After your response I have had a dig further into the issue and it turned out I had additional set of rules coming in within our build pipeline that was raising a warning. Apologies for my mistake,  the `--verify-no-changes` behavior works as expected with the --severity level.
