### ISSUE TITLE
Upgrade tooling to latest .NET 7 preview and add Package Source Mapping

### ISSUE THREAD

**Issue by lbussell** [dotnet/format#1602]
This repo's main branch still builds with .NET 7 preview 2. It should be upgraded to .NET 7.0 preview 5.

https://github.com/dotnet/format/blob/dfa8a55c16d66b94f88eaa52d9467e941860956e/global.json#L8

Upgrading tooling to Preview 4 or newer will introduce warning [NU1507](https://devblogs.microsoft.com/nuget/introducing-central-package-management/#warning-when-using-multiple-package-sources), since format uses central package management without specifying any package source mapping.

This is blocking source-build, so we will need to carry a patch for this repo to ignore NU1507 until this is fixed.

See the documentation for package source mapping: https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping

**Comment by JoeRobich** [comment]
@lbussell We typically stick to public previews. Since Preview 5 hasn't been released, is there a particular version we should be targeting? Do we need to move SDKs if we add the package source mapping?

**Comment by lbussell** [comment]
@JoeRobich Oops, I see, I must be jumping the gun on that. I updated the issue. I believe that any version Preview 4 or above will work with package source mapping, as specified in this blog post: https://devblogs.microsoft.com/nuget/introducing-central-package-management/#central-package-management.

**Comment by JoeRobich** [comment]
We have merged a change which adds the package source mapping. I've also opened a PR to move us to Preview 4.
