### ISSUE TITLE
File encoding on auto-generated files

### ISSUE THREAD

**Issue by dnperfors** [dotnet/format#1799]
dotnet format checks the file encoding as it is set in .editorconfig

We found out that auto generated files are not checked and fixed. (Files starting with `// <auto-generated>`)
When saving the file inside VisualStudio, the encoding is changed to how it is configured in .editorconfig.

**Comment by sharwell** [comment]
> We found out that auto generated files are not checked and fixed

This is by design. You can force dotnet format to ignore this designation using the command line argument `--include-generated`.
