### ISSUE TITLE
Update net7.0 TFM references to net8.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/format#1802]
In order to be source-build compliant for the .NET 8.0 release.  All projects targeting a `net7.0` TFM must be upgraded to `net8.0`.  It is preferred that a new [`NetCurrent` Arcade property](https://github.com/dotnet/arcade/pull/12161) be utilized as it eliminates this type of maintenance work for every release.

**Comment by mthalman** [comment]
@jmarolf - Can you take a look at this? It looks like there hasn't been a recent merge of Arcade (https://github.com/dotnet/format/pull/1795) which would be needed to enable this.

**Comment by oleksandr-didyk** [comment]
@jmarolf - source-build [pre-built detection](https://github.com/dotnet/source-build/blob/main/Documentation/eliminating-pre-builts.md#what-is-a-prebuilt) would also require this upgrade to be able to bump certain dependencies.

Currently resolving pre-builts is a considerable pain-point for the source-build team and we would greatly appreciate if you could take a look at the upgrade / refer someone else that could perform the work.

Thank you!

**Comment by oleksandr-didyk** [comment]
@jmarolf - apologizes for the ping again, but it would be great if we could get some acknowledgement from you regarding this task (i.e. if this is something that you can perform or we would need to contact another dev). Thanks a lot in advance!

**Comment by jmarolf** [comment]
@sharwell to redirect.

**Comment by MichaelSimons** [comment]
This was completed with https://github.com/dotnet/format/pull/1812.
