### ISSUE TITLE
IDE0073 not getting applied

### ISSUE THREAD

**Issue by cabadam** [dotnet/format#1827]
We have found that "dotnet format" is not applying changes for the file_header_template value configured in the .editorconfig (rule IDE0073).

I've uploaded a small repo that demonstrates the issue:
https://github.com/cabadam/TestIDE0073

From within Visual Studio, I can go to the top of the class file that is missing a header, and I do get the light bulb popping up where I can then select the IDE0073 item and direct it to fix all in solution.  It then correctly identifies and changes the headers on the 2 appropriate files (the file with no header, and the file with the wrong header).

However, if I instead run the dotnet format command, no files are modified.
`dotnet format --diagnostics IDE0073 TestIDE0073.sln --verbosity diagnostic`

Output from the command is attached.
[dotnet-format-ide0073.txt](https://github.com/dotnet/format/files/11349229/dotnet-format-ide0073.txt)

**Comment by JoeRobich** [comment]
I wonder if your VS instance has a severity for this diagnostic which is set separately from the .editorconfig. If you add `dotnet_diagnostic.IDE0073.severity = warning` to the .editorconfig, the files are fixed as expected.

**Comment by cabadam** [comment]
You appear to have nailed it - moving it up to warning in the .editorconfig made it apply as expected.  A couple thoughts:

- The docs for --severity do not list "suggestion" as an option.  It just lists options for error/info/warn.  I tried giving both "suggestion" and "suggestions", but it rejected both.
- It would be outstanding if, when explicitly told to apply a specific rule, it TOLD me it was ignoring it anyway.

**Comment by just-ero** [comment]
Hello. I stumbled upon this while looking for some `file_header_template` related information.  

It appears that this problem no longer exists?  
`IDE0073` is applied when running `dotnet format --diagnostics IDE0073`.  
The `--severity` option lists `info` as a possible argument, which applies `suggestion`-level rules.

**Comment by octaviordz** [comment]
For information, this is the behavior that I see with `dotnet format`, the header file is not being applied. I tried `dotnet format --diagnostics IDE0073` did not work, tried `dotnet format --severity info` did not work, tried updating the .editorconfig adding `dotnet_diagnostic.IDE0073.severity = error` did work.

**Comment by xtqqczze** [comment]
IDE0073 is not being reported when `dotnet_diagnostic.IDE0073.severity = error` is present in global AnalyzerConfig file, e.g. `.globalconfig`.

Command used:

```sh
dotnet format analyzers --diagnostics IDE0073 --verify-no-changes
```
