### ISSUE TITLE
Confused - "£" converted to "�"

### ISSUE THREAD

**Issue by dazinator** [dotnet/format#1893]
My CI build just ran a dotnet format on my code (luckily PR branch) and pushed up the changes.

One of the files it corrected orignally had this c# code

```csharp
 _mocked.Setup(x => x.GetCurrenciesAsync(It.IsAny<string[]>(), default))
                         .Returns(Task.FromResult<IList<CurrencyDto>>(new List<CurrencyDto>()
                         {
                            { new CurrencyDto(){ Id= 1, IsBase = true, IsUnit = true, Symbol = "£", Code = validCurrencyCode , Name= validCurrencyCode} }
                         }));
```

The formatted version, the `£` symbol has been changed to "�":

```csharp
 _mocked.Setup(x => x.GetCurrenciesAsync(It.IsAny<string[]>(), default))
                         .Returns(Task.FromResult<IList<CurrencyDto>>(new List<CurrencyDto>()
                         {
                            { new CurrencyDto(){ Id= 1, IsBase = true, IsUnit = true, Symbol = "�", Code = validCurrencyCode , Name= validCurrencyCode} }
                         }));
```

dotnet format is run during our azure devops build pipeline, its run on an ubuntu docker container

here is header info

```

Starting: dotnet format
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.221.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/azp/_work/_tool/dotnet/dotnet format --no-restore --verbosity diagnostic
  The dotnet runtime version is '6.0.6'.
  The dotnet CLI version is '6.0.301'.
  Using MSBuild.exe located in '/azp/_work/_tool/dotnet/sdk/6.0.301/'.
  Formatting code files in workspace '/azp/_work/1/s/src/foo.sln'.

```

**Comment by sharwell** [comment]
Can you verify that the source files in the repository are encoded as UTF-8 _with byte order mark_? This is the default encoding for C# files and is used to prevent this issue from occurring.

**Comment by dazinator** [comment]
@sharwell thanks I will investigate.

If this is the case then, given a developer may accidentally remove the BOM from a file or change its encoding (assuming they use a funny editor), it would be desirable to enforce that `.cs` files are checked into and out of git with UTF8 plus BOM in order to ensure that dotnet format can be run safely on those files when checked out on the build server. Perhaps there is some way to enforce this with `.gitattributes` and `editorconfig` - I will look into that, but if anyone has any solutions for this I would be keen to hear them.

**Comment by JoeRobich** [comment]
@dazinator In .editorconfig you can specify a charset for .cs files. dotnet-format with the `--verify-no-changes` flag could be the validation, as charset is part of the `dotnet whitespace` formatting.

```ini
[*.cs]
charset = utf-8-bom
```

**Comment by dazinator** [comment]
> @dazinator In .editorconfig you can [specify a charset](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#charset) for .cs files. dotnet-format with the `--verify-no-changes` flag could be the validation, as charset is part of the `dotnet whitespace` formatting.
> 
> ```ini
> [*.cs]
> charset = utf-8-bom
> ```

Thank you I will try this. It seems there is some history on this, e.g https://github.com/editorconfig/editorconfig/issues/297#issuecomment-480799733

**Comment by sharwell** [comment]
Resolving as answered
