### ISSUE TITLE
[NETSDKE2E]With net8 rc1 sdk installed, Test .NET format project failed with error : Tests failed: C:\Users\v-danche\format\artifacts\TestResults\Debug\dotnet-format.UnitTests_net8.0_x64. html [net8.0|x64] [C:\Users\v-danche\format\tests\dotnet-format.UnitTests.csproj]

### ISSUE THREAD

**Issue by vdanche** [dotnet/format#1934]
1.Install NET8 RC1 SDK(8.0.100-rc.1.23417.18(runtime- 8.0.0-rc.1.23414.4)) from https://aka.ms/dotnet/8.0.1xx-rc1/daily/dotnet-sdk-win-x64.exe,
 2. Checkout the dotnet-format repo. git clone https://github.com/dotnet/format.git
 3. Update the gobal.json by removing the "sdk" configuration
before
![image](https://github.com/dotnet/format/assets/65637796/b5c874c7-ae1c-41b4-90f2-0077a86a8391)

After:
![image](https://github.com/dotnet/format/assets/65637796/6ae62293-d2e8-41d3-9de3-f48acbc87545)
4.Run Restore.cmd.
5.Run Build.cmd.
6.Run Test.cmd.

**Expected Result:**
Restore build and test project successfully.

**Actual Result:**
Restore build successfully, but test project failed with below error
![image](https://github.com/dotnet/format/assets/65637796/0e49aa9d-3078-4b51-b6f2-fa0af5c2569b)

dotnet--info:
![image](https://github.com/dotnet/format/assets/65637796/cf722d67-1432-4b07-a3ad-6e380c194305)

**Comment by JoeRobich** [comment]
The failures are likely due to needing to update the NuGet package version. 

https://github.com/dotnet/format/blob/1a9a3b61b7ed91ea17e69ceb1f954d431f0a1415/eng/Versions.props#L28-L30

Try setting the `NuGetVersion` to `6.8.0-preview.1.68`.

**Comment by vdanche** [comment]
@JoeRobich After setting NuGetVersion to 6.8.0-preview.1.68 in ..format/eng/Versions.props file, Test project successfully.
![image](https://github.com/dotnet/format/assets/65637796/ffd93549-622b-4ac8-907c-876b9e112d8f)

**Comment by vdanche** [comment]
@JoeRobich Test project also successfully with the default config(6.8.0-preview.1.41) on machine with NET8 RC1 SDK(8.0.100-rc.1.23417.18(runtime- 8.0.0-rc.1.23414.4) installed
![image](https://github.com/dotnet/format/assets/65637796/8f27a46c-5bbc-4c85-b106-1559dc19033c)

**Comment by JoeRobich** [comment]
@vdanche Thanks for confirming!
