### ISSUE TITLE
[NETSDKE2E]With net8 rc1 sdk installed, Restore .NET format project failed with error NU1102:Unable to find package Microsoft.NETCore.App.Runtime.win-x64 with version (= 8.0.0-rc.1.23419.4) [C:\Users\v-danche\format\format.sln] 

### ISSUE THREAD

**Issue by vdanche** [dotnet/format#1943]
1.Install NET8 RC1 SDK(8.0.100-rc.1.23421.2(runtime- 8.0.0-rc.1.23419.4)) from Artifacts: [Pipelines - Run 20230821.1-8.0.100-rc.1.23421.2-189171 artifacts (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2248709%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-danche%40microsoft.com%7Cf1fa259d47864ab6331108dba35430cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638283354442531583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=36sOg62usulBSSxMfS2c5ukSrvGzHOCvtY9WwCTR1Kc%3D&reserved=0)
2. Checkout the dotnet-format repo. git clone https://github.com/dotnet/format.git
3. Update the gobal.json by removing the "sdk" configuration
before
![image](https://github.com/dotnet/format/assets/65637796/5babef94-6eb6-49ce-9bd7-3300d0198094)
After:
![image](https://github.com/dotnet/format/assets/65637796/f8cf1732-9a00-48ce-be69-5483a3bd81de)

4. Run Restore.cmd

Expected Result:
Restore project successfully.

Actual Result:
Restore failed with error NU1102
![image](https://github.com/dotnet/format/assets/65637796/3632f0ab-3e16-42b0-bb61-5404e7ab29c2)

Note:
Correct Feed has been added into Nuget.config file.
https://pkgs.dev.azure.com/dnceng/internal/_packaging/8.0.100-rc.1.23421.2-shipping/nuget/v3/index.json

dotnet --info:
![image](https://github.com/dotnet/format/assets/65637796/ac5af6ed-f472-4faf-8535-95b7510dbbef)

**Comment by marcpopMSFT** [comment]
Did you include the private feed when trying this out?

**Comment by marcpopMSFT** [comment]
Ahh missed that the first time. I see it out.  That package is in that feed so I'm not sure why the restore command isn't finding it:https://dev.azure.com/dnceng/internal/_artifacts/feed/8.0.100-rc.1.23421.2-shipping/NuGet/Microsoft.NETCore.App.Runtime.win-x64/overview/8.0.0-rc.1.23419.4

Is the feed not configured correctly? Is something broken with authenticated feeds? Is something broken in the restore.cmd?

**Comment by marcpopMSFT** [comment]
I quickly tested self-contained build with the private feed in a sandbox and it worked so auth feeds are working. Maybe something with restore.cmd?

**Comment by JoeRobich** [comment]
Was the nuget package mapping updated to reference the new feed?

**Comment by vdanche** [comment]
@JoeRobich @marcpopMSFT @richaverma1 Today we checked with using the same SDK and feed, this issue not repro now.
![image](https://github.com/dotnet/format/assets/65637796/30d81321-2a85-4114-8ebb-39af976536fa)
