### ISSUE TITLE
Provide `dotnet format` API as non-tool NuGet package 

### ISSUE THREAD

**Issue by FrediKats** [dotnet/format#1951]
I'd like to use dotnet format as part of another C# application. But dotnet format has `<PackAsTool>true</PackAsTool>`.

Is any way to add dotnet format as nuget package to other project? Any plans to support this case? Any suggestion/workaround?

**Comment by JoeRobich** [comment]
Hi @FrediKats, we have no plans of releasing dotnet-format as a library for use in other projects. You can always shell out to the dotnet format tool instead.

**Comment by FrediKats** [comment]
Thx for answer.
