### ISSUE TITLE
Stop dotnet format from removing thrown exceptions

### ISSUE THREAD

**Issue by talbananaz** [dotnet/format#2061]
```c#
catch (Exception ex)
        {
            throw ex;
        } ``` 

        
        gets changed to 
        
      ```c#    catch (Exception ex)
        {
            throw;
        }```

**Comment by sharwell** [comment]
`dotnet format` is not responsible for this change. The project in question has enabled an analyzer (I am not sure which one) which includes a code fix to make this alteration. The configuration for invoking `dotnet format` and/or the configuration for this project would need to be updated to reflect the developer preferences in order for this change to not occur.
