### ISSUE TITLE
Why don't you finalize the version? The latest version is 2021

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/format#2083]
Why don't you finalize the version? The latest version is 2021

**Comment by sharwell** [comment]
Hi @EngRajabi,

I'm not sure I understand the request here. Can you clarify?

Thanks!

**Comment by JoeRobich** [comment]
@EngRajabi dotnet-format now [ships as part of the .NET SDK](https://github.com/dotnet/format/issues/1268) and there will be no new versions pushed to NuGet. If you have a need to install a development build, there are [instructions in the Readme](https://github.com/dotnet/format/issues/1268).
