### ISSUE TITLE
Questions around Contributing to the Repo

### ISSUE THREAD

**Issue by Bartleby2718** [dotnet/format#2132]
I just encountered the same bug as in #2125. Given that VS is able to fix it, I don't think it's a Roslyn issue. I'd like to reproduce this by adding a test to this solution and hopefully fix it, but I'm having trouble setting this repo up locally.

The first thing I had to fix after cloning the repo locally was updating `global.json` to match my local .NET SDK version. The second thing was not being able to find `Microsoft.DotNet.Arcade.Sdk`, which I think will be fixed by following https://stackoverflow.com/a/65337211. Apparently I haven't spent too much time on this yet, but these issues make me wonder if there's any documentation on local dev setup.

Hence my questions:
1. Do you have any documentation on local dev setup? 
2. Is there a list of issues that should be prioritized?
3. How do you deploy/publish the changes? Is it automatically published upon merge to main? 
4. Are there any notes for contributors besides the Code of Conduct? For example, should the destination branch be `main` or some other release branch?

Thanks in advance!

**Comment by Bartleby2718** [comment]
Some things I've done after posting:
- Run `dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json --name dotnet-eng`
- Update the version of `Microsoft.DotNet.Arcade.Sdk` to a version in https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.Arcade.Sdk/overview/
- Add `<FlagNetStandard1XDependencies>false</FlagNetStandard1XDependencies>` to `Directory.Build.props` to work around a build failure
- Turn on `Use previews of the .NET Core SDK` in VS

At this point I think I was able to run tests, although one of them was failing.

**Comment by Bartleby2718** [comment]
@sharwell @arkalyanms @JoeRobich?

**Comment by arkalyanms** [comment]
@sharwell would you advise @Bartleby2718 on issue priority for contributions. 

@Bartleby2718 main is the branch to target, but @Cosifne is moving this repo into the SDK repo as a part of https://github.com/dotnet/sdk/pull/38857. So we are holding off on merging fixes until that PR lands.

**Comment by RussKie** [comment]
>  You will need to manually install the version of the .NET SDK listed in global.json for the commit you check out locally:

@sharwell this is not true.
This repo is using the Arcade SDK, with that `restore.cmd` is downloading the required version of the SDK.
![image](https://github.com/dotnet/format/assets/4403806/d070b2d3-3615-460c-b4bc-1308ddaa2275)


> 
> If you cannot install that version, the repository should still build from the command line. It may not be possible to use the solution inside Visual Studio prior to [dotnet/designs#303](https://github.com/dotnet/designs/pull/303) being approved, implemented, and delivered.
> 

This is not entirely correct either.
You will need to add helper scripts (like many other dotnet repos have done) to launch both VS and VS Code with the repo's SDK. E.g.:
* To start VS: https://github.com/dotnet/winforms/blob/main/start-vs.cmd
* To start VS Code: https://github.com/dotnet/winforms/blob/main/start-code.cmd
* To start VS Code on Linux or WSL: https://github.com/dotnet/aspire/blob/main/start-code.sh
