### ISSUE TITLE
Why not fail in error condition ?

### ISSUE THREAD

**Issue by techygarg** [dotnet/format#219]
I am using the latest version of the tool. One thing I want to clarify why it does not show an error if it is mentioned in the editorconfig, e.g.: **dotnet_style_object_initializer = true:error**.

The second thing does the tool support all attributed defined at [roslyn-editorconfig](https://github.com/dotnet/roslyn/blob/master/.editorconfig) ?

**Comment by JoeRobich** [comment]
@techygarg Sorry for the late reply. dotnet-format only supports a subset of the code style options at the moment. You can find a list of supported options on our Wiki - https://github.com/dotnet/format/wiki/Supported-.editorconfig-options
