### ISSUE TITLE
Add --folder option to `dotnet format` command

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/format#2210]
## Motivation:
I need to sync namespaces for a specific folder in a .NET project. While the `dotnet format whitespace --folder` command offers functionality for formatting whitespaces within a folder, a similar option does not exist for dotnet format when handling namespaces.

## Expected Behavior:
The following command should sync namespaces for the specified folder:

```bash
dotnet format ./src/ --diagnostics IDE0130 --folder
```
This command would apply the IDE0130 diagnostic (Namespace Sync) across all files in the ./src/ directory, ensuring consistent namespaces within the folder.

**Comment by JoeRobich** [comment]
@NikiforovAll The `--folder` options forgoes a design time build meaning we do not have complete semantic information. This is OK for whitespace formatting but not all analyzers will function properly with incomplete information. We could certainly determine some subset of codestyle analyzers which would give correct results, but there might be the impression that a complete check was performed.

An alternative would be to use the `--include` option. It supports globs meaning you could use it to limit included files to a particular folder. Something like `dotnet format {path-to-solution} --diagnostic IDE0130 --include ./src/**`

**Comment by NikiforovAll** [comment]
Hi @JoeRobich,

I really like the `--include` approach! Do you accept contributions for this? If so, I'd love to help out. Also, any idea of the timeline for when this feature might be available?

**Comment by JoeRobich** [comment]
@NikiforovAll dotnet-format already has support for `--include`. You can find the list of options at https://github.com/dotnet/sdk/tree/main/src/BuiltInTools/dotnet-format#common-options-for-all-commands

**Comment by NikiforovAll** [comment]
Works like a charm, thanks! 

`dotnet format --diagnostics IDE0130 --verify-no-changes --severity info --include ./path-to-folder/`
