### ISSUE TITLE
Cannot write problem matcher for VS Code custom task

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/format#247]
I'm trying to run `dotnet format` in a VS Code custom task. But, there's not enough detail in the output to write a decent [problem matcher](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher).

**tasks.json**
```typescript
"problemMatcher": {
    "fileLocation": ["relative", "${workspaceFolder}"],
    "pattern": {
        "regexp": "^\\s*Formatted code file '(.*)'.$",
        "file": 1,
        "line": 2,
        "column": 3,
        "severity": 4,
        "message": 5
    }
}
```

The output doesn't provide enough of a file path for `fileLocation`. It doesn't provide line or column numbers. And it doesn't provide a specific message.

```
$ dotnet format --check --dry-run
  Formatting code files in workspace 'C:\Users\anthony\example\src\Example\Example.csproj'.
  Formatting code files in project 'Example'.
  Formatted code file 'Startup.cs'.
  Format complete.
```

# Considerations

The important points to consider when redesigning the output:

 * The output should include _workspace relative_ paths, no matter how I specify the `--workspace`
 * The output should include line and column number where the violation occurs
 * The output should not include severity, since that's not a relevant concept; the user can choose whichever is appropriate for their project: `warning` or `error`
 * The output should include not just the [rule name](https://github.com/dotnet/format/wiki/Supported-.editorconfig-options), but whether the rule was required or not and how it was violated (more thought on this is probably required.. maybe append "not required" for `false` rules and "required" for `true` rules?)

## Simple Problem Matcher
https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher

**template**
```
[workspace relative file path](line,col): [rule name]
```

**output**
```
$ dotnet format --check --dry-run
Formatting code files in workspace 'C:\Users\anthony\example\Example.sln'.
  src\Example\Startup.cs(26,22): space between parentheses not required
  src\Example\Controllers\ExampleController.cs(100,31): new line before open brace required
Format complete.
```

**tasks.json** ([regex101](https://regex101.com/r/ewOwqy/1))
```typescript
{
    "label": "format",
    "command": "dotnet",
    "type": "process",
    "args": ["format", "--check", "--dry-run"],
    "problemMatcher": {
        "fileLocation": ["relative", "${workspaceFolder}"],
        "severity": "warning",
        "source": "dotnet format",
        "pattern": {
            "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "message": 4,
        }
    }
}
```

## Multiline Problem Matcher
https://code.visualstudio.com/Docs/editor/tasks#_defining-a-multiline-problem-matcher

It's possible for a single file to have multiple violations and even for a single line in that file to have multiple violations. So, we need to output text that can be matched properly. I _wonder_ if repeated lines and matches are simply added up in the problem windows. If so, then flat repeated output, not "stylish" nested output, might be best.

**output**
```
$ dotnet format --check --dry-run
Formatting code files in workspace 'C:\Users\anthony\example\Example.sln'.
  src\Example\Startup.cs(26,22): space between parentheses not required
  src\Example\Startup.cs(26,42): new line before open brace required
  src\Example\Controllers\ExampleController.cs(100,31): new line before open brace required
Format complete.
```

**tasks.json**
_No change necessary! Repeated lines worked! I tested using a text file containing the expected output and a fake `cmd.exe` task._

```typescript
{
    "label": "format",
    "command": "cmd",
    "type": "process",
    "args": ["/c", "type", "example.txt"],
    "problemMatcher": {
        "fileLocation": ["relative", "${workspaceFolder}"],
        "severity": "warning",
        "source": "dotnet format",
        "pattern": {
            "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "message": 4,
        }
    }
}
```

## Background/Watching Problem Matcher
https://code.visualstudio.com/Docs/editor/tasks#_background-watching-tasks

What about when we want to run formatting constantly in the background? Maybe via `dotnet watch`? We need to implement the task slightly differently. Luckily, dotnet format already outputs a begin and end statement.

**tasks.json**

_I tweaked the fake `cmd.exe` task to output the contents of that file in a loop. You can modify the contents during the wait time. The problem matcher seems to have some trouble clearing out the last problem for a given file, but if you stack up multiple problems and remove them one-by-one, you can see the general behavior._

```typescript
{
    "label": "format",
    "command": "cmd",
    "type": "process",
    "args": ["/c", "FOR /L %G IN (1,1,100) DO timeout /T 10 & type example.txt"],
    "isBackground": true,
    "problemMatcher": {
        "fileLocation": ["relative", "${workspaceFolder}"],
        "severity": "warning",
        "source": "dotnet format",
        "pattern": {
            "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "message": 4,
        },
        "background": {
            "activeOnStart": true,
            "beginsPattern": "^Formatting code files in workspace\\s+'(.*)'\\.$",
            "endsPattern": "^Format complete\\.$"
        },
    }
}
```

**Comment by AnthonyMastrean** [comment]
Related to #90 (but I want to make sure I have _everything_ I need for a problem matcher)

**Comment by jmarolf** [comment]
@AnthonyMastrean 	could you go into detail on what format you would like for this? Would you like us to just output json to the console and/or a file?

**Comment by AnthonyMastrean** [comment]
So, I don't know how to shovel json into the problem panel, short of writing an extension. I don't think that's part of anyone's plan? What's your roadmap? Is Code support a priority? If so, then specifically formatted text output plus a custom task and problem matcher seems like a kind of shortcut. 

Something like:

```
src/Example/Baz.cs (13, 42): <friendly name or short description of violation>
```

I want to double check this against the way the compiler prints file paths and line/column, because why shouldn't it be similar. I guess a single line can have multiple rule violations, so that should be parseable, too (there's a problem matcher feature for that).

I can clean this up later ;)

**Comment by jmarolf** [comment]
@AnthonyMastrean 	yeah, someone will always needs to write an extension to get this to work.  I'll look at the VS Code api and see what it requires.  My goal would be to make this sort of thing easy to do.  My hope would be that tool authors would need to write a lot of code to parse this result.

**Comment by AnthonyMastrean** [comment]
I updated the issue to reflect the various scenarios. However, if anyone wants to let `format` automatically fix their code in the background, that's already supported!

```typescript
        {
            "label": "format",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "--project ./Example.sln",
                "format",
            ],
            "isBackground": true,
            "problemMatcher": []
        }
```

**Comment by JoeRobich** [comment]
@AnthonyMastrean Can you try out the latest build from MyGet?
```
dotnet tool install -g dotnet-format --version 3.1.36303 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```

**Comment by AnthonyMastrean** [comment]
It works! But, not with `$msCompile`. That's probably OK because I can't mix and match the built in problem matchers and background tasks and I'm more inclined to run this as a background task.

```javascript
    "problemMatcher": {
        "fileLocation": ["relative", "${workspaceFolder}"],
        "severity": "warning",
        "source": "dotnet format",
        "pattern": {
            "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "message": 4,
        },
        "background": {
            "activeOnStart": true,
            "beginsPattern": "^Formatting code files in workspace\\s+'(.*)'\\.$",
            "endsPattern": "^Format complete\\.$"
        },
    }
```

**Comment by sharwell** [comment]
@AnthonyMastrean please consider sending a pull request to this project adding comments in code to any places that are sensitive to this, and/or refactoring the output sections to go through helper methods that ensure the output always has the expected form.

**Comment by rynowak** [comment]
Thanks for figuring this out @AnthonyMastrean 

I'm successfully using this matcher as well on github actions.

![image](https://user-images.githubusercontent.com/1430011/75615950-50624800-5aff-11ea-90fe-4059e851fc68.png)

```yaml
name: Format

on:
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
     
    - name: dotnet tool restore
      run: dotnet tool restore

    - name: add dotnet format problem matcher
      run: echo "::add-matcher::build/dotnet-format-problem-matcher.json" 
      
    - name: dotnet format
      run: dotnet format -w <mysln>.sln --check --dry-run -v diag
```

```json
{
    "problemMatcher": [
        {
            "owner": "dotnet-format",
            "severity": "warning",
            "pattern": [
                {
                    "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "message": 4
                }
            ]
        }
    ]
}
```

**Comment by JoeRobich** [comment]
@AnthonyMastrean Thanks for putting together these samples!
