### ISSUE TITLE
dotnet-format.exe 3.0.0 is looking for 3.0.0-beta4-19105-10 assemblies

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/format#31]
**Version Used**: 

dotnet-format.exe 3.0.0

**Steps to Reproduce**:

1. Install dontet-format 3.0.0 - `dotnet tool install --global dotnet-format --version 3.0.0 `
2. run dotnet-format
3. 

**Expected Behavior**:

Runs!

**Actual Behavior**:

```
The application to execute does not exist: 'C:\Users\me\.dotnet\tools\.store\dotnet-format\3.0.0-beta4-19105-10\dotnet-format\3.0.0-beta4-19105-10\tools\netcoreapp2.1\any\dotnet-format.dll'.
```

**Comment by JoeRobich** [comment]
@paulomorgado & @KexyBiscuit - We have pushed a new release build (3.0.2) to NuGet that should resolve this issue. Let us know if you run into any more issues . Thanks!
