### ISSUE TITLE
Check file encoding

### ISSUE THREAD

**Issue by shargon** [dotnet/format#347]
It would be very useful to be able to check if the files are in utf8 (with or without boom).

Is it possible to do it now?

**Comment by shargon** [comment]
Thanks so much

**Comment by RehanSaeed** [comment]
I have the following in my `.editorconfig` file:

```
[*]
charset = utf-8
```

When I run `dotnet format`, all my `.cs` files are changed from UTF-8 to Western encoding. What am I doing wrong?

**Comment by jmarolf** [comment]
@RehanSaeed which version of dotnet-format are you using?

**Comment by RehanSaeed** [comment]
`4.1.131201`

**Comment by jmarolf** [comment]
@RehanSaeed does this issue still reproduce if you install the (beta) 5.0 version?

```cmd
dotnet tool install -g dotnet-format --version 5.0.142902 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
```

**Comment by RehanSaeed** [comment]
It's still converting UTF-8 encoded files to Western European (Windows).

**Comment by jmarolf** [comment]
Thanks, it likely has to do with which code pages are available on your machine. Can you open up a new issues giving:

- Your operating system and version
- the set of language packs you have installed
- You default language version.

**Comment by celluj34** [comment]
I am having this same issue:

OS and Version:
![image](https://user-images.githubusercontent.com/10264021/103670377-1e9be800-4f3f-11eb-803a-a41ff9215903.png)

dotnet format version:
![image](https://user-images.githubusercontent.com/10264021/103670358-1643ad00-4f3f-11eb-959f-f073253d4ee4.png)

Languages installed:
![image](https://user-images.githubusercontent.com/10264021/103670474-3a9f8980-4f3f-11eb-8919-30369caf4f99.png)

Let me know if there's more info you need.

**Comment by JoeRobich** [comment]
@celluj34 @RehanSaeed Could either of you share files or steps that repro this behavior? The steps I tried are as follows. Ran through these on both MacOS and an up to date Windows 10.

1. Run `dotnet new console`
2. Run `code .`
3. Save Program.cs with the UTF-8 encoding
4. Add .editorconfig 
```ini
root = true

[*]
charset = utf-8
```
5. Run `dotnet format -v d`

No files formatted.

**Comment by celluj34** [comment]
Two files are exhibiting the issue for me: https://drive.google.com/drive/folders/1EoPXUBa67AR537ZLHCJsqFIj0wP7is0t?usp=sharing

![image](https://user-images.githubusercontent.com/10264021/103687999-cc66c100-4f56-11eb-904e-02171a650a94.png)

My .editorconfig file does have the `charset` set (and I did verify it's the _only_ place it's set): 
![image](https://user-images.githubusercontent.com/10264021/103688079-e56f7200-4f56-11eb-8520-a0677b52f84e.png)

**Comment by JeroMiya** [comment]
@JoeRobich Could you take a second look at this? I don't see a new issue being filed, and this issue that @celluj34 describes can still be reproduced with version `5.0.211103` of dotnet-format.

I'm experiencing the same issue. I have an .editorconfig with:
```
[*]
charset = utf-8
```
And running dotnet-format with --fix-whitespace will convert some files from "UTF-8 with signature" or "UTF-8 without signature" to "Western European (Windows)".

At first I thought it was noticing that the UTF-8-BOM encoded files didn't match the .editorconfig setting, but reformatted it to the wrong encoding. But, if I try setting it to UTF-8 without signature and run the formatter again, it still changes it to Western European (Windows).

**Comment by JoeRobich** [comment]
@JeroMiya Who is reporting the encoding as Western European (Windows)? Without a BOM, the heuristic used to guess a file encoding in editors like VS Code can sometimes be confused when two encodings would produce the equivalent bytes on disk. If it is VSCode telling you the files are Western Europe (Windows), then [you can configure the `files.guessableEncodings` setting](https://github.com/microsoft/vscode/issues/36951#issuecomment-420953324) to restrict the guesses to encodings that you know you use.

**Comment by JeroMiya** [comment]
The git changes window in Visual Studio is reporting it, but I'll check out your suggestion tomorrow and report back. Thanks!

**Comment by jerviscui** [comment]
Have the same problem.
@JeroMiya

**Comment by jerviscui** [comment]
**Test 1:**
1. I executed `dotnet format`.
2. In VS Git differents, It suggests the file encoding is GB2312:
![image](https://user-images.githubusercontent.com/6396748/127965285-b9a8b706-127a-4910-8844-89efedbdf531.png)
But, In VS Code display is UTF-8.

**Test 2:**

1. If input some chines in the file.
2. Use `dotnet format`.
3. Git differents display the formatted file encoding is UTF-8.
![image](https://user-images.githubusercontent.com/6396748/127966870-6c7a1e5b-8a7b-4c67-933b-c01ff332331d.png)

**Test 3:**
When I use Resharper Code Cleanup,  the formatted file encoding is correct!
![image](https://user-images.githubusercontent.com/6396748/127967118-c8ce2739-d917-4975-b044-b9f1f160e92d.png)


In addition, if I commit Test 1 changes, then use Resharper Code Cleanup, The file will not change again.

**Comment by dnperfors** [comment]
I had the same issue, but looking deeper into it I found that the original encoding was wrong (UTF8-BOM) and the new encoding was correctly set (UTF-8). In other words it is working correctly, but VisualStudio can't handle these changes very well.
