### ISSUE TITLE
--folder option missing from installed version

### ISSUE THREAD

**Issue by JasonSeanMorrow** [dotnet/format#355]
I attempted to install and use dotnet-format, but was unable to use the --folder option.  Help showed a list of all the options shown on the How To Use resource on the top page, with the exception of -f.  I tried uninstalling and reinstalling with versions 3.1.37601 and 3.0.4 but neither showed -f as a viable option.  Using dotnet-format with the other options (-w, --dry-run) worked as expected.

The project I'm working on has a number of plugins and for merging and verification purposes I would very much like to avoid reformatting across the entire project.  Is --folder not an option available in the latest stable build, or have I made a mistake at some point in installation or usage?

**Comment by JoeRobich** [comment]
We haven't had a release with the `--folder` option yet. You can install a development build from our myget page.
```
dotnet tool install -g dotnet-format --version 3.1.42902 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```

**Comment by JasonSeanMorrow** [comment]
Thank you for your prompt response, and the sample code for installing the development build.  I will explore using it.
