### ISSUE TITLE
Clarify which languages are supported

### ISSUE THREAD

**Issue by nilekirk** [dotnet/format#36]
Please clarify at the top of Readme.md which languages are supported. Also change the error message ``Unhandled exception: System.InvalidOperationException: Cannot open project ... because the file extension '.fsproj' is not associated with a language.`` to something less ridiculous.

**Comment by glen-nicol** [comment]
I have a mixed C#/F# solution. How would you recommend I filter out the F# projects to avoid the constant warning output? The fsproj file is what causes the warning even if I use an ```--exclude *.fs``` or equivalent recursive pattern.
