### ISSUE TITLE
Dry run output format options

### ISSUE THREAD

**Issue by xt0rted** [dotnet/format#379]
I'm working on a tool that takes the output from a dry run and reports on it. Right now I'm having to parse this with a regex to get the file path, line number, and message. Is there a way to output this as json, or to write my own output formatter and use it as a plugin?

**Comment by jmarolf** [comment]
seems reasonable to offer json output at the least.  I would accept a PR for this.

**Comment by jpshrader** [comment]
Any additional thoughts on the structure of this? Just FileName/Path, line number, and message?

I can take a crack at this when I find some time.

**Comment by jmarolf** [comment]
no objections from me. I would happily accept a pr here

**Comment by jpshrader** [comment]
I've got a branch ready, but looks like I have a permissions issue

**Comment by jmarolf** [comment]
thanks @jpshrader!You should be able to [fork ](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)this repo and [create a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) without any additional permissions. This is the workflow that I have used here. Is this not working for you?

**Comment by jpshrader** [comment]
@jmarolf Ah, okay, gotcha. I was trying to push to a branch in this repo. Thanks! Apologies for the few days delay, I was only release duty last week.

I've opened the [PR here](https://github.com/dotnet/format/pull/495). I added some comments on some questions for you maintainers, so feel free to leave some red ink on it.

**Comment by JoeRobich** [comment]
This functionality was implemented in #495
