### ISSUE TITLE
Run compiler diagnostics if any active code fix declares support for them

### ISSUE THREAD

**Issue by sharwell** [dotnet/format#398]
If any active code fix contains a CS* (C#) or BC* (Visual Basic) diagnostic ID in the set of supported diagnostics, we need to make sure these compiler diagnostics are gathered.

Filed as a follow-up to #281

**Comment by jmarolf** [comment]
right, we will. my understanding is that today no code style warning that we ship needs this. We'll also need to investigate how poorly this effects performance

**Comment by sharwell** [comment]
I believe we have some code fixes in place for fixing some compiler warnings. It should be a straightforward change to check the declared diagnostic IDs though to make sure we are ready for a case if/when a user adds a code fix to the mix that uses them (e.g. a code fix that adds NRT annotations to explicitly-typed local variables).
