### ISSUE TITLE
The files option doesn't allow to format files wants to format all workspace

### ISSUE THREAD

**Issue by pepone** [dotnet/format#403]
Using `--files` to format a single file doesn't work 
```
dotnet format --files Ice\Collections.cs
  Could not find a MSBuild project file or solution file in 'D:\3.7\ice-master\csharp\src'. Specify which to use with the --workspace option.

dotnet-format --version
3.1.37601+256f37159dc60b29f76999749f57f4338324f102
```

**Comment by JoeRobich** [comment]
You can now specify  the `--folder` option for formatting files without using a project or solution file. Used in conjunction with the `--folder` options, the `--files` option will allow you to narrow this further to a list of specific files.
