### ISSUE TITLE
Ability to check formatting / code style without writing to disk

### ISSUE THREAD

**Issue by roman-petrov** [dotnet/format#41]
Hello! 

Many existing code formatting tools ( [Prettier](https://prettier.io/), [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) ) support checking code format without modifying source files. 

Currently to only check formatting I can implement some wrapper which will clone source code, run `dotnet-format' on this clone and then compare formatted files with original source code. But this seems to be too complex approach for such scenario. 

Do you plan to implement feature allowing to check format in `dotnet-format` (might be a console application option)?...

**Comment by jmarolf** [comment]
If you run `dotnet-format --dry-run -v diag` it will list the set of files that it found formatting discrepancies for.  I assume you want it to insead print out the lines that are invalid? It unclear from the links what your desired behavior is.

**Comment by roman-petrov** [comment]
@jmarolf , thanks for quick response. Sorry, but I didn't knew that `--dry-run` option exists, maybe it would help in case above... 

Just wondering: will `dotnet-format --dry-run -v diag` process exit with non-zero exit code if it found files that have to be formatted?

The scenario: I would like to use `dotnet-format` in continuous integration process or pre-commit git hook so CI build/commit should fail if `dotnet-format` founds any files that should be reformatted.

**Comment by jmarolf** [comment]
@roman-petrov 	I am not opposed to this but I would need to see a more complete proposal.  

Today `dotnet-format` returns `0` if it was able to load code and run.  It will return `0` even if there are no files modified.  Code `1` is returned if any error is encountered. Most well behaved tools in windows return code `0` to mean there was no error in the programs execution.

You proposal sounds like adding a new options, let's call it `--are-all-files-formatted` for the sake of argument.  With this option specified `dotnet-format` will return `0` if no files need formatting or the exact number of files that do need formatting.  I assume we would return `-1` for the failure case here.

**Comment by roman-petrov** [comment]
Actually, there is a long-living and widely used front-end code format tool [Prettier](https://prettier.io/). So my proposal is to implement the option that works exactly as `prettier --check`. 

This CLI option is described in prettier documentation at <https://prettier.io/docs/en/cli.html#check>

Would this be enough for `dotnet-tool` enhancement proposal?...

**Comment by jmarolf** [comment]
@roman-petrov 	this looks complete enough. Can you submit a PR?

**Comment by roman-petrov** [comment]
@jmarolf , sure, I will submit a PR in a few days when I get some time to work on it.

**Comment by sharwell** [comment]
Another option is to install FormattingAnalyzer in the project and set the severity to warning or error. This will validate formatting in the build just as well as dotnet-format, but when using the IDE you'll also be prompted to automatically fix violations.

**Comment by roman-petrov** [comment]
Thanks, @sharwell, I never heard about FormattingAnalyzer before. Hope my upcoming PR with `--check` option for `dotnet-format` still would be useful.

**Comment by jmarolf** [comment]
@roman-petrov 	please feel free to submit a PR for the feature.  The hope is that people can use `dotnet format` for situations where they don't want to modify their build.

**Comment by roman-petrov** [comment]
@jmarolf thank you, I will open a PR early next week.

**Comment by svrooij** [comment]
I like this new feature idea and would like to let you guys know that I would like to use it!

**Comment by roman-petrov** [comment]
I just opened a PR for this improvement. Can anyone please take a look?

**Comment by JoeRobich** [comment]
A build with this feature is now available on myget.
```
dotnet tool install -g dotnet-format --version 3.0.4-prerelease.19162.2 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```

**Comment by roman-petrov** [comment]
great, thank you!

**Comment by robinmanuelthiel** [comment]
How long does it usually take, until we see new features on NuGet? @JoeRobich
