### ISSUE TITLE
Run Roslyn Analyzers and CodeFixes

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/format#416]
Configuration for diagnostic severity can now be expressed in .editorconfig files. dotnet format should be able to run diagnostics and apply fixes for those of a specified severity.

As a first step dotnet format could support the known set of CodeStyle diagnostics and fixes in Roslyn.
As a further enhancement it could run Analyzers installed via NuGet.

**Comment by OneCyrus** [comment]
any update on this? i think that's the main feature everyone is waiting for.

**Comment by JoeRobich** [comment]
To support analyzers and fixes the following work items need to be completed:
 1. Move to Roslyn .editorconfig support (https://github.com/dotnet/format/pull/590) which is currently blocked by a performance regression.
 2. Implement Analyzer & CodeFix discovery that doesn't require Roslyn IVTs
 3. Move the analysis and codefix support over from the feature/analyzers branch

**Comment by jmarolf** [comment]
closed with https://github.com/dotnet/format/pull/713
