### ISSUE TITLE
Extensionpoint for custom rules

### ISSUE THREAD

**Issue by dotnetgeek** [dotnet/format#43]
Hi,

I've played around with the .editorconfig and this tool and I find it really helpful (like meantioned on other thread).

Currently I'm thinking about if it will be valuable to have some extension points here to be apple to apply rules that are not supported by the .editorconfig.

Maybe something that it is possible to implement some custom "CSharpOnlyFormattingRule" like this here https://github.com/dotnet/codeformatter/blob/master/src/Microsoft.DotNet.CodeFormatting/Rules/UsingLocationRule.cs  that will be loaded and also applied after the setting of the .editorconfig has been applied. I know that my refrence is possible with .editorconfig, it is more like how I found it useful. 

This would over the option to apply custom rules to the code that is specific for a company.

Are there any plans? 

Thanks
Daniel

**Comment by jmarolf** [comment]
I'll let @JoeRobich chime in here, but I personally would want a centralized set of rules.  Basically, if it is good enough for your project to use why not make it a buit-in rule for all .NET tooling?

At some point we may add the ability to define and apply custom analyzers/codefixes to a project but that is a ways out.

**Comment by JoeRobich** [comment]
@dotnetgeek Thanks for logging this request. This is something that we've discussed, but there are a lot of questions about how we would go about implementing it. 

At the moment, I feel like the highest priority task for dotnet format would be to grow the support for editorconfig options to include the [Language Styles and Naming Styles](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) options already supported in VS.

To speak directly to the 'using locations' example, I've been working on adding this as a code style option in Roslyn (also editorconfig) and hope to have it ready for one of the VS2019 point releases. - https://github.com/dotnet/roslyn/pull/30760

**Comment by dotnetgeek** [comment]
Hi @JoeRobich, @jmarolf 

thank you for your answers. I would a agree that having the support on the same level as VS should be the highest priority.

For now I can live with that and use a custom - self written - tool to apply additional rules. I hope that at some point I can use it within the same Cli.

Thanks,
Daniel

**Comment by OneCyrus** [comment]
custom rules would be awesome. As it looks like this project is not under active development, open a way to use stylecop rules could revive the project and grow a userbase.

**Comment by sharwell** [comment]
I believe all NuGet-installed analyzers that include code fixes should be supported by this tool, so I'm very much in favor of this request with standard analyzers+code fixes _being_ the extension point.

**Comment by jmarolf** [comment]
@sharwell I agree that when we do this that will likely be the way we implement it

**Comment by JoeRobich** [comment]
Closing this issue. Analyzer support is being tracked at https://github.com/dotnet/format/issues/416
