### ISSUE TITLE
Formatting not Working for Webapplication

### ISSUE THREAD

**Issue by surajts** [dotnet/format#435]
The formatter is not working for web application project. I am seeing the following output. The version that I am using is "4.0.40103+07078c3be865ad9e1ed2e02054e920dd0fd94628"
`C:\code>dotnet-format --files "presentation\web\proj\about.aspx.cs" -w presentation\web\proj\webapplication.csproj -v diag -fs
  Formatting code files in workspace 'C:\code\prism\presentation\web\proj\webapplication.csproj'.
  Loading workspace.
  Complete in 1498ms.
  Determining formattable files.
  Complete in 14ms.
  Running formatters.
  Analyzing code style.
  Analysis complete in 592ms.
  Complete in 677ms.
  Formatted 0 of 0 files.
  Format complete in 2194ms.`

**Comment by jmarolf** [comment]
@surajts  What specifically is not working? can you give me a list of expected and actual results?

**Comment by JoeRobich** [comment]
Hi @surajts,

dotnet format runs against the .NET Core msbuild. This means it doesn't have access to Full Framework build targets which may be what is breaking your scenario.

We have delisted the 4.0.40103 build from myget as we are working on getting diagnostic code fixes into the master branch. If you can downgrade to 3.1.57101 and give up the diagnostic fix support, it has a `-f` folder flag which bypasses msbuild for determining files and should allow you to run against code found in the specified folder.

-Joey

**Comment by surajts** [comment]
oh ok, I am running these against 4.7.2 . So probably that is the issue. It actually formats them for class libraries but only have issue with webapplication project types.

**Comment by surajts** [comment]
> @surajts What specifically is not working? can you give me a list of expected and actual results?

When I run the formatter it is not formatting the aspx.cs files. BTW this is .net 4.7.2 and the project type is webapplication

**Comment by jmarolf** [comment]
@surajts thanks!

**Comment by JoeRobich** [comment]
> only have issue with webapplication project types

@surajts Unfortunately ASP.NET on the Full Framework is the exact case that is unsupported. The build targets don't exist for the .NET Core msbuild so it isn't able to enumerate the files in that project. Downgrading and using the folder switch is the current workaround for this situation.

**Comment by surajts** [comment]
> Hi @surajts,
> 
> dotnet format runs against the .NET Core msbuild. This means it doesn't have access to Full Framework build targets which may be what is breaking your scenario.
> 
> We have delisted the 4.0.40103 build from myget as we are working on getting diagnostic code fixes into the master branch. If you can downgrade to 3.1.57101 and give up the diagnostic fix support, it has a `-f` folder flag which bypasses msbuild for determining files and should allow you to run against code found in the specified folder.
> 
> -Joey

Thanks. with -f option this particular version is working.
