### ISSUE TITLE
Command line interface is inconsistent with the rest of the dotnet tool suite

### ISSUE THREAD

**Issue by BrennenSprimont** [dotnet/format#489]
All other dotnet commands take the folder or file of the project/solution as the first position argument. dotnet format requires a `-w` flag to specify the project to act on.

Consider conforming interface to the rest of the dotnet tools.

Other dotnet tool interface examples:
`dotnet build ./Source`
`dotnet build ./Source/MyProject.csproj`
`dotnet run ./Source`
`dotnet publish ./Source`
`dotnet test ./Test`

Dotnet format expected interface:
`dotnet format ./Source`

Dotnet format actual interface:
`dotnet format -w ./Source`

**Comment by jmarolf** [comment]
@JoeRobich what do you think about having a default that finds projects the same what `dotnet build` does with the other options available as a fallback if that fails?
