### ISSUE TITLE
Support Folder and File Exclusions

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/format#500]
Ability to list folder or files that should be excluded from formatting.

**Comment by jpshrader** [comment]
@JoeRobich Mind if I take a crack at this?

**Comment by JoeRobich** [comment]
@jpshrader That would be great. Start by posting your proposed design here and we can talk through it.

**Comment by jpshrader** [comment]
@JoeRobich I was thinking it might look something like:

1. Accept a comma-separated list of file/folder paths (`--exclude <stuff>`), which like the `--report` option, is passed along to [CodeFormatter.cs](https://github.com/dotnet/format/blob/master/src/CodeFormatter.cs) via the `FormatOptions` object.

2. Add a similar `if` block to the [GetDocumentAndOptions](https://github.com/dotnet/format/blob/master/src/CodeFormatter.cs#L286-L289) method in `CodeFormatter`, which excludes files if they fall under any of the excluded files/folders.

That logic could also go a layer up in in the [DetermineFormattableFiles](https://github.com/dotnet/format/blob/master/src/CodeFormatter.cs#L249-L270), but I think the above approach is cleaner.

**Comment by sandyarmstrong** [comment]
Personally, I would find it very useful to be able to specify exclusions in some sort of configuration file, so that using the tool locally or via CI would yield the same results without having to make a tedious list of arguments.

I do think an `--exclude <stuff>` approach is great. But I hope it's a step on the road to configuration-based formatting.

BTW how evil would it be to put this kind of configuration data in `global.json`? :)

**Comment by JoeRobich** [comment]
> I would find it very useful to be able to specify exclusions in some sort of configuration file

@sandyarmstrong  I opened https://github.com/dotnet/format/issues/520 to track the configuration file proposal. Feel free to make suggestions.

**Comment by jpshrader** [comment]
Reading through comments in #520, to @sandyarmstrong's [point](https://github.com/dotnet/format/issues/520#issuecomment-582669311):
>... to capture files that aren't part of the main solution, but then need to be able to avoid files (for example, template files, or certain other shared/copied files) that are not really "ours" to format.

It might be valuable to allow consumers to use wildcards in their paths to account for these types of situations (`*.template.cs`, for instance). I don't think the other options for folder/files support this, so apologies if this idea has been swatted down in the past.

**Comment by JoeRobich** [comment]
@jpshrader The proposal looks good. I feel like we'll have to add an `include` alias for the `files` option. =)
Let's start with your initial two proposal and we can look into file globs as a later enhancement.

**Comment by jmarolf** [comment]
> It might be valuable to allow consumers to use wildcards in their paths to account for these types of situations (*.template.cs, for instance). I don't think the other options for folder/files support this, so apologies if this idea has been swatted down in the past.

Wildcard filtering is already supported in `.editorconfig` files today. I continue to be concerned that we are inventing yet-another-editorconfig file type

**Comment by jpshrader** [comment]
> Wildcard filtering is already supported in .editorconfig files today. I continue to be concerned that we are inventing yet-another-editorconfig file type

True, good point, that escaped my mind. I retract my original statement then.

**Comment by JoeRobich** [comment]
@jpshrader Thanks again. Closing this issue.
