### ISSUE TITLE
Support configuring dotnet-format with a configuration file

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/format#520]
As we add more options to the configuration it is increasingly tedious to type them all out at the command line. 

- We should add support for reading in options from a "format.json" file. 
- We should look for the configuration file in the current working directory.
- We should support multiple configurations stored as top-level properties. The configuration can be specified from the command line with a new `-c|--configuration {name}` option. A "default" option can be configured which will be applied whenever a configuration is not specified.
- The option's property name should match the long name for the option.
- Options that support multiple values provided as a comma separated string can be expressed as either a comma separated string or as an array of values.
- Options are optional in the configuration and will take their default value if missing or if `null` is specified for their value.

Example "format.json":
```json
{
    "default": {
        "folder": "./src",
        "workspace": null,
        "dry-run": false,
        "check": false,
    },
    "all": {
        "workspace": "format.sln",
        "dry-run": false,
        "check": false,
        "files": null
    },
    "validate": {
        "folder": "./src",
        "workspace": null,
        "dry-run": true,
        "check": true,
        "files": [ ]
    }
}
```

**Comment by sandyarmstrong** [comment]
My only addition here would be to make it a hidden file similar to `.gitconfig` and `.editorconfig`. I'd suggest `.dotnetformatconfig` or `.formatconfig`.

I really like the multiple configurations idea here. Cool stuff!

**Comment by jmarolf** [comment]
I am not opposed to this in theory. My main concern is that we create an alternative to `.editorconfig`. In most cases I would expect someone to update the `.editorconfig` in their project to exclude/include files. I can see the rare case where I have some set of submodules that I need to configure, but my hope is that we first find a way to specify formatting options so that `dotnet format`, Visual Studio for Mac, VS Code, and Visual Studio can all do the same thing.

All those concerns aside, I would tentatively accept a PR for this.

**Comment by sandyarmstrong** [comment]
My desires here are motivated by VSmac's build needs:

* We have several submodules, so there's that. We can't trivially use this tool as a CI check as long as we have submodules without perfect formatting. (the new `--report` option would at least allow us to process the output and do our own path exclusions...so far the output is only file names so we can't filter based on that)
* We would like to use the `--folder` option to capture files that aren't part of the main solution, but then need to be able to avoid files (for example, template files, or certain other shared/copied files) that are not really "ours" to format.

**Comment by jmarolf** [comment]
@sandyarmstrong and so I understand, is the intent that all those submodules eventually get their own `.editorconfigs` with `root` set so dotnet-format just does the right thing? Is this a point-in-time issues as we move all of the formatting in all the submodules over? Or are these dependencies never going to be updated?

Either way I can see the submodule case being a good justification. I am still wary of adding more options beyond this though.

**Comment by sandyarmstrong** [comment]
@jmarolf whether a project's submodules have `.editorconfig`s or not, it shouldn't necessarily impact the project's CI if those submodules have files that violate formatting rules.

Of course it's best if each submodule has its own CI that also enforces proper formatting (and some of them do), but that's not always something that can be controlled. There are any number of unfortunate reasons why a submodule might have formatting problems on a given day. In my opinion that should be the submodule's problem, not (in this example) VSmac's.

**Comment by jmarolf** [comment]
> whether a project's submodules have .editorconfigs or not, it shouldn't necessarily impact the project's CI if those submodules have files that violate formatting rules.

It should be necessary for the submodules to have `editorconfig` files. You can exclude submodules from styling via the `editorconfig` in your root project.

**Comment by sandyarmstrong** [comment]
> It is not necessary for the submodules to have editorconfig files. You can exclude submodules from styling via the editorconfig in your root project.

I understand that, but that's not the behavior I want. I want to be able to work in my main project solution, edit files that are in submodules, and have them get formatted according to the appropriate `.editorconfig` rules. Then it's up to me (and submodule CI) to worry about whether formatting was correct.

But when I make a change in the main repository, and CI uses `dotnet format` to verify formatting, mistakes in the submodule should be able to be ignored.

**Comment by JoeRobich** [comment]
@sandyarmstrong Fun thing I learned is that System.CommandLine, which we use for command line option parsing, already supports loading options from a response file. Verified this capability is already in the public release builds. You can refer to #557 if you want an example of how they are formatted. Let me know if this doesn't work for your use cases.

**Comment by JoeRobich** [comment]
@sandyarmstrong  Closing this issue since response files can be used for configuration. Feel free to reopen if this doesn't work for your use case.
