### ISSUE TITLE
Don't know which files are formatted

### ISSUE THREAD

**Issue by challen0** [dotnet/format#58]
I noticed when running the tool, there's no way to tell which files were actually formatted just from reading the output. If I'm reading the code correctly, it prints 'Formatting file x' before it knows if changes will be made. It also looks like those messages are only available with verbosity of diagnostic. It would be nice to be able to run `--check` or `--dry-run` and know which files I need to address.

**Comment by JoeRobich** [comment]
I think logging out the name of formatted files would be a good feature. Logging it as information is probably appropriate, that would have it printed when using the detailed verbosity.

**Comment by JoeRobich** [comment]
This is now available on myget
```
dotnet tool install -g dotnet-format --version 3.0.4-prerelease.19174.1 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```
