### ISSUE TITLE
Add final newline false positive

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/format#581]
When I run dotnet-format 3.3.111304 on the following app with the following editorconfig I get the following error `ConsoleApp1\Program.cs(9,2): Add final newline.`. My understanding is that the final newline already exists (see screenshot). Is this a false positive?

```
namespace ConsoleApp1
{
    class Program
    {
        static void Main()
        {
        }
    }
}

```

```
[*]
insert_final_newline = false
```

![dotnet-format - Add final newline false positive](https://user-images.githubusercontent.com/8421414/75594153-66afcb80-5a4d-11ea-87ab-7ba3a9b2ad55.png)

**Comment by sharwell** [comment]
This is a bug in the message displayed for the `false` case. The actual message for this case should be:

> Remove final newline
