### ISSUE TITLE
Question: Diagnostic Verbosity

### ISSUE THREAD

**Issue by tonysneed** [dotnet/format#60]
When I pass `-v diag` flag (with `--dry-run`), I can see that 1 file is formatted, but I don't see what formatting rules were violated and where. Is there a way to show this info?

**Comment by jmarolf** [comment]
Not today I believe @JoeRobich

**Comment by JoeRobich** [comment]
Not today. The formatter doesn't treat each rule individually and instead fixes all whitespace formatting issues in one operation. We then report when a file's content doesn't match the formatted content.

**Comment by tonysneed** [comment]
Got it - thanks!
