### ISSUE TITLE
Fomatter not using .editorconfig in the folder

### ISSUE THREAD

**Issue by legionaryu** [dotnet/format#625]
Hi folks.

I've been trying to use the **dotnet-format** tool to format my whole solution at once, but I've decided to try it in some dummy files before.
The version I'm using is 3.3.111304+7c8f67a570f5fde6a247704733d6742f93c0fa48 and I'm testing with the following command `dotnet format -f .`, but for some reason my **.editorconfig** file seems to be ignored, as the formatter is replacing _tabs_ for _spaces_ .
You can check below, how the folder is structured:
```
- Folder
 |-- Code.cs
 |-- Code2.cs
 |-- .editorconfig
```
My **.editorconfig** content is the following:
```
root = true
charset = utf-8
end_of_line = lf
tab_width = 4
indent_size = tab
indent_style = tab
insert_final_newline = true
```

Am I doing it wrong? Should I put the **.editorconfig** file in another folder?

Cheers,

**Comment by jmarolf** [comment]
@JoeRobich is this related to https://github.com/dotnet/roslyn/issues/22601?

**Comment by JoeRobich** [comment]
@legionaryu Thanks for trying out dotnet format. Other than the `root` property, we expect all other configuration to be beneath a section header. This behavior matches the [.editorconfig spec for file processing](https://editorconfig-specification.readthedocs.io/en/latest/#file-processing).

The following should be a working version of your .editorconfig.
```
root = true

[*.*]
charset = utf-8
end_of_line = lf
tab_width = 4
indent_size = 4
indent_style = tab
insert_final_newline = true
```

**Comment by legionaryu** [comment]
@JoeRobich, thank you so much! 

Now I can use it to normalize the endings and encoding in my whole solution.
