### ISSUE TITLE
Roslyn syntax format vs Visual Studio format

### ISSUE THREAD

**Issue by foximoxi** [dotnet/format#639]
I see a difference between Roslyn formatting:
CSharpSyntaxTree.ParseText("C# code here").GetRoot().NormalizeWhitespace().ToFullString()
and VIsual Studio formatting style.

Is it possible to normalize the style between these two tools?
For example:

var doc = new Document<dynamic> { Id = id, Content = obj };
var doc = new Document<dynamic>{Id = id, Content = obj};

**Comment by jmarolf** [comment]
`NormalizeWhitespace` is a helper method to add _some_ whitespace to a generated syntax tree. If you are parsing code from an existing file or string whitespace will already need to exist so there is no need to call this method.

in this code:
```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
class Program {
    static void Main(string[] args) {
        CompilationUnitSyntax root = CompilationUnit()
                                    .WithMembers(
                                        SingletonList<MemberDeclarationSyntax>(
                                            ClassDeclaration("C")));
        SyntaxTree tree = CSharpSyntaxTree.Create(root);
    }
}
```

Attempting to print the code to a string will produce (without spaces)

```
classC{}
```

Adding `NormalizeWhitespace` will add some basic whitespace to the nodes according to some hard coded defaults.
```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
class Program {
    static void Main(string[] args) {
        CompilationUnitSyntax root = CompilationUnit()
                                    .WithMembers(
                                        SingletonList<MemberDeclarationSyntax>(
                                            ClassDeclaration("C")))
									.NormalizeWhitespace();
        SyntaxTree tree = CSharpSyntaxTree.Create(root);
    }
}
```

```csharp
class C { }
```

The generallly expected way to handle complex formatting cases is to use the [`Formatter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.formatting.formatter?view=roslyn-dotnet) class. I would open issues on dotnet/roslyn if you have questions about the correct way to use the Formatter api. Or you can ask on the roslyn [gitter](https://gitter.im/dotnet/roslyn) channel

**Comment by JoeRobich** [comment]
Closing as this question has been answered.
