### ISSUE TITLE
New line inserted before C# 8 switch expression open brace

### ISSUE THREAD

**Issue by emzeq** [dotnet/format#640]
`dotnet format` is inserting a new line before switch expression open braces with `csharp_new_line_before_open_brace = none` in `.editorconfig`.

Expected:
```csharp
var result = operation switch {
    "+" => a + b,
    "-" => a - b,
    "/" => a / b
};
```

Actual:
```csharp
var result = operation switch
{
    "+" => a + b,
    "-" => a - b,
    "/" => a / b
};
```

dotnet format version: 3.3.111304+7c8f67a570f5fde6a247704733d6742f93c0fa48

**Comment by JoeRobich** [comment]
@emzeq Thanks for the report. Since we rely on the Roslyn code formatter this will be fixed when https://github.com/dotnet/roslyn/issues/36913 is resolved.

**Comment by JoeRobich** [comment]
Closing as the 5.x nightly builds should now have this fix.
