### ISSUE TITLE
Git pre-commit hook and file paths

### ISSUE THREAD

**Issue by dazinator** [dotnet/format#643]
Hello

I am trying to set up a git pre-commit hook to run dotnet-format using the --files options to format only files staged for commit.

My repo directory structure looks like:

/src/.editorconfig
/src/project/foo.cs

My git precommit hook looks like this:

```
#!/bin/sh; C:/Program\ Files/Git/usr/bin/sh.exe
echo "running precommit hook"
LC_ALL=C
# Select files to format
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
# Format all selected files
echo "$FILES"
xargs dotnet-format -v diag -f .\src --include $FILES 

# Add back the modified files to staging
echo "$FILES" | xargs git add
exit 0

```

Scripting really isn't my speciality,and I have cobbled this together from a variety of sources. I am running on windows. However I observe the following issue:

The file paths from git are all relative to the repo root / working directory so in this case `src/project/foo.cs`

However `dotnet-format` is formatting the ".\src" folder (that is where the editorconfig is kept). Because of this, it wants a path like `project/foo.cs`. So passing in the git directories unaltered results in dotnet-format not matching any files.

How should I be dealing with this? Is there a simple way to strip the root folder from paths passed from git?

Note I can work around this issue by restructuring things. I can move the editor config file to the root of the repo, and run `dotnet-format -f . --include $FILES` so that dotnet-format runs in the root of the repo and therefore all git paths match what it expects, but I'd like not to have to restructure in this way just to fit this tool...

**Comment by dazinator** [comment]
Hmm I figured it out. I altered the `sed` command to replace "/src" in the git path with "/"
Here is the full working githook in case it helps anyone else:
```
#!/bin/sh; C:/Program\ Files/Git/usr/bin/sh.exe
echo "running precommit hook"
LC_ALL=C
# Select files to format
#FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g')
GITFILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g') 
DOTNETFORMATFILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's|src/||') # remove root src dir from git file path when passing to dotnet format
[ -z "$DOTNETFORMATFILES" ] && exit 0
# Format all selected files
echo "$DOTNETFORMATFILES"
#$FILES | xargs dotnet-format -v diag -f src --include $FILES 
xargs dotnet-format -v diag -f src --include $DOTNETFORMATFILES 
#git ls-files :/{src,tests}/*.cs | xargs dotnet-format -v diag --files

#dotnet-format -v diag -w src
# Add back the modified files to staging
echo "$GITFILES" | xargs git add
exit 0
```

I am sure this can be improved. Please let me know if you make improvements.

**Comment by JoeRobich** [comment]
@dazinator dotnet format doesn't have to be run from the same folder as the .editorconfig. Applicable .editorconfig files are determined by walking up from each code file. Using `xargs dotnet-format -v diag -f . --include $DOTNETFORMATFILES` should work fine.

**Comment by JoeRobich** [comment]
Closing as this question has been answered.
