### ISSUE TITLE
Allow running on generated code

### ISSUE THREAD

**Issue by sharwell** [dotnet/format#670]
**dotnet-format** should have a command line flag that allows the formatter to run on files that would otherwise be considered generated. This will allow the tool to be used by the code generation tools themselves to produce properly-formatted code.

**Comment by jmarolf** [comment]
You should be able to do this today with the `--files` option

**Comment by JoeRobich** [comment]
@jmarolf We will need to work around the generated code check.

**Comment by jmarolf** [comment]
ah, got it
