### ISSUE TITLE
Support for all convention categories

### ISSUE THREAD

**Issue by isc30** [dotnet/format#68]
(this topic was initially discussed [here](https://github.com/dotnet/roslyn/issues/34449))

It would be great if we could support every convention category and not only 'formatting conventions'.
[List of all convention categories](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)

As an example, supporting rules like `dotnet_style_require_accessibility_modifiers` would open a new world of possibilities

**Comment by challen0** [comment]
I think @JoeRobich wants to cover more of those things. You can read some more in #40.

**Comment by JoeRobich** [comment]
@isc30 Thanks for voicing your support. As @challen0 mentioned, we are going to let #40 track the request for supporting more code style options. Please give it a vote. =)
