### ISSUE TITLE
Timeline for other editorconfig options?

### ISSUE THREAD

**Issue by mristin** [dotnet/format#683]
Hi!
Thank you very much for developing dotnet-format! It is a great tool and we are trying to integrate it into our CI pipeline.

Could you give some more information about when you plan to support other editorconfig options? (Is it a matter of weeks, months, years?)

**Comment by jmarolf** [comment]
which editorconfig options do you want us to support?

**Comment by mristin** [comment]
Hi @jmarolf ,
It would be good to have `csharp_prefer_braces`.

**Comment by jmarolf** [comment]
I see thanks!

@JoeRobich I believe that for these styles:
```
csharp_prefer_braces 
csharp_prefer_simple_default_expression 
csharp_prefer_simple_using_statement 
csharp_prefer_static_local_function
csharp_preferred_modifier_order 
csharp_style_prefer_index_operator 
csharp_style_prefer_range_operator 
csharp_style_prefer_switch_expression 
```

We only consider them upon generating code in the IDE. Lets use this issue to track being able to apply these `csharp_prefer` options.

**Comment by JoeRobich** [comment]
@mristin with the 5.0 release we now support the full range of code style options when using the `--fix-style` option. Closing this issue.
