### ISSUE TITLE
Support for pre-commit project

### ISSUE THREAD

**Issue by jvstein** [dotnet/format#692]
I wrote a hook for integrating with the [pre-commit](https://pre-commit.com/) project. It's here: https://github.com/jvstein/pre-commit-dotnet-format

I've been using it while developing on Linux, but haven't tested it on Windows or macOS. It's very much dependent on Docker, using a prebuilt docker image, because [pre-commit doesn't support C# yet](https://pre-commit.com/#supported-languages). I'd be very happy to integrate it into the project, but wasn't sure how to go about adding the docker dependency to the build system.

**Comment by JoeRobich** [comment]
@jvstein Thanks for sharing your work. pre-commit looks like a nice tool. I've used Husky for the same purpose on previous projects.

I've been thinking that one of the bits of missing documentation for dotnet-format is how to integrate with various build systems. There have been other issues opened where people have contributed their GitHub Action or AzDO yaml configurations. What might be nice is to start a new document (`/docs/integrations.md` maybe) that collects this information. 

We would be thrilled if you wanted to start the document and share your configuration for pre-commit with a little write-up.

**Comment by jmarolf** [comment]
I totally endorse this. I think we start with a doc that we can point people at the tells them how to set this up and see where things go from there.

**Comment by jvstein** [comment]
That sounds like a great place to start. I'm happy to get that doc started.

**Comment by rkm** [comment]
pre-commit has just added support for the dotnet language, so I've opened a PR to add a hooks file https://github.com/dotnet/format/pull/872.

**Comment by rkm** [comment]
Until #872 is merged (or not), I've mirrored this repo to add pre-commit support [here](https://github.com/rkm/mirrors-dotnet-format). This also allows auto-updating to follow the master/main branch so that you don't have to wait for the next release (use `pre-commit autoupdate --bleeding-edge`)
