### ISSUE TITLE
Whitespace differences between Windows and Linux

### ISSUE THREAD

**Issue by virzak** [dotnet/format#705]
Below is code which passes a check on Linux (Ubuntu) but fails it on Windows

```csharp
ProcessStartInfo startInfo = new ProcessStartInfo("git.exe")
{
    Arguments =                          "rev-parse --abbrev-ref HEAD",
    UseShellExecute = false,
    RedirectStandardInput = true,
    RedirectStandardOutput = true,
    WorkingDirectory = new FileInfo(GetType().Assembly.Location).DirectoryName
};
```

Should probably fail on both?
Had a look quickly at the code, but didn't see a test case for something like this.

**Comment by JoeRobich** [comment]
@virzak Have you configured `end_of_line` in your .editorconfig? Also, if you are checking out the source with Git, how is `core.autocrlf` configured on the failing Windows box?

**Comment by virzak** [comment]
@JoeRobich I don't think I was clear...

This is about spaces, not `git`

Extra spaces in 
```
Arguments =                          "rev-parse --abbrev-ref HEAD",
```
are the issue.
