### ISSUE TITLE
[Suggest] Add option for overriding line endings

### ISSUE THREAD

**Issue by JeroMiya** [dotnet/format#731]
I know there are other command line tools that will do this, but it would be very convenient if there were an option in dotnet-format to override the source file's line endings to a specified one. So, for example, let's say I'm running dotnet-format on code-generated C# files that, for whatever reason, have LF line endings (e.g. a badly written npm tool) even on windows. I'd like the option to override the original line endings with CRLF while formatting.

**Comment by JoeRobich** [comment]
@JeroMiya I think you are in luck. We support the .editorconfig property `end_of_line`. See for more details - https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#end_of_line

**Comment by JeroMiya** [comment]
Right on! thanks!
