### ISSUE TITLE
--fix-analyzers and --fix-styles not found.

### ISSUE THREAD

**Issue by ChrisBertrand** [dotnet/format#732]
When trying to use the --fix-analyzers and --fix-styles commands they are not found in the tool. Has this been added to the documentation prematurely?

**Comment by JoeRobich** [comment]
Hi @ChrisBertrand,

Sorry, that functionality has not made it into a public release but has made it into the master branch and the nightly development builds. 

You can try this out yourself by installing our latest development build with the caveat that the feature isn't 100% baked. For instance Full Framework or NetStandard projects may report compilation errors around unresolved dependencies.

```
dotnet tool install -g dotnet-format --version 5.0.135801 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```

-Joey

**Comment by ChrisBertrand** [comment]
Question answered.
