### ISSUE TITLE
Feature request: Port VS's Organize Usings facility to dotnet-format

### ISSUE THREAD

**Issue by am11** [dotnet/format#744]
This feature request is about organizing `using namespace` from command-line tool. This feature is often used in Visual Studio in context of 'code formatting'.

Visual Studio:

![image](https://user-images.githubusercontent.com/3840695/89336409-03803000-d6a2-11ea-9997-2e613825fc50.png)
![image](https://user-images.githubusercontent.com/3840695/89336088-881e7e80-d6a1-11ea-91cc-bdec7944f6d7.png)

Desired Options from dotnet-format:

```diff
dotnet-format:
  dotnet-format

Usage:
  dotnet-format [options] [<project>]

Arguments:
  <project>    The solution or project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -f, --folder <folder>           Whether to treat the `<project>` path as a folder of files. [default: ]
  --files, --include <include>    A list of relative file or folder paths to include in formatting. All files are formatted if empty. [default: System.String[]]
  --exclude <exclude>             A list of relative file or folder paths to exclude from formatting. [default: System.String[]]
  --check, --dry-run              Formats files without saving changes to disk. Terminates with a non-zero exit code if any files were formatted.
  --report <report>               Accepts a file path, which if provided, will produce a json report in the given directory. [default: ]
+  -r, --remove-usings            Removes unnecessary usings.
+  -s, --sort-usings[=system]     Sorts usings alphabetically. With value 'system', places 'System' directives first.
  -v, --verbosity <verbosity>     Set the verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]
  --version                       Show version information
  -?, -h, --help                  Show help and usage information
```

**Comment by JoeRobich** [comment]
@am11 We have support for organizing imports using the following .editorconfig settings - https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019#organize-using-directives

To support removing unused imports, I was hoping that there would be a working fixer for IDE0005. However, we can conditionally run `document.GetLanguageService<IRemoveUnnecessaryImportsService>().RemoveUnnecessaryImportsAsync(document, cancellationToken)` as part of `--fix-style` if we detect IDE0005 is configured.

**Comment by mgedda** [comment]
> 
> 
> @am11 We have support for organizing imports using the following .editorconfig settings - https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019#organize-using-directives
> 
> To support removing unused imports, I was hoping that there would be a working fixer for IDE0005. However, we can conditionally run `document.GetLanguageService<IRemoveUnnecessaryImportsService>().RemoveUnnecessaryImportsAsync(document, cancellationToken)` as part of `--fix-style` if we detect IDE0005 is configured.

Sorry for hijacking this issue thread (I am new to GitHub), but I am unable to run `dotnet format` with the `--fix-style` option and it is not stated as a valid option in the help text. But since you mention it @JoeRobich only a week ago in this thread I guess it hasn't been removed and I cannot find any information other than this page https://github.com/dotnet/format/blob/master/docs/Supported-.editorconfig-options.md on how to enforce the .Net Language and Naming conventions?

**Comment by am11** [comment]
I could not find the `--fix-style` option either. It looks like `--fix-style` is a new option, which has not been released yet.

A minor nitpick: `dotnet-format` _almost_ follows the Unix-y tools [arguments convention](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) (like 99.9978% 😎). Following the <kbd>principle of least surprise</kbd>, it would be nice to fully follow the convention. e.g. short-hand of `--fix-style` is set to `-fs`, which is not the short-hands/aliases. The convention is simple; alias has only a single letter next to single hyphen: `-f` or `-s` (or some other unreserved alphabet), or drop the alias altogether (as they are optional). The reason for this convention is that many tools interpret `-fs` as `-f -s` batched together and it just looks just surprising for reader in the documentation. (had a similar comment about `dotnet new -lang` argument, which is the only oddity in its help menu).

**Comment by JoeRobich** [comment]
@am11 The 5.x builds which include CodeStyle and Analyzer support are not ready for a public release yet. You can install a development build by following these instructions https://github.com/dotnet/format#installing-development-builds. 

I agree with the suggestion to remove the aliases for --fix-style and --fix-analyzers. I'll open a PR for it.
