### ISSUE TITLE
Is it possible to point to editorconfig file?

### ISSUE THREAD

**Issue by eddynaka** [dotnet/format#769]
Looking at the options I couldn't find a way to specify the editorconfig location.

Is that possible?

**Comment by sharwell** [comment]
.editorconfig is a hierarchy-based format. It will automatically use the one(s) applicable to the source files getting formatted according to their paths on disk.

**Comment by eddynaka** [comment]
i see...what would happen if in my folder i have something like this:
src
- java
- c#
   - .editorconfig

dotnet-format would find that file?

**Comment by jmarolf** [comment]
yes please report a bug if this does not work
