### ISSUE TITLE
The --check option returns a zero exit code if it can't fix an issue

### ISSUE THREAD

**Issue by bourquep** [dotnet/format#770]
Repro:

- Add `dotnet_diagnostic.IDE0052.severity = warning` to `.editorconfig`
- Have a class with a private member that is never read
- Run `dotnet format Foo.csproj --fix-style info --fix-analyzers info --check`
- Observe that the tool reports the `IDE0052` warning, but is unable to fix it
- Observe that the tool reports a zero (success) exit code
- Expected: should report a non-zero exit code

```
  Services/GreeterService.cs(14,46): Private member 'GreeterService._logger' can be removed as the value assigned to it is never read. (IDE0052)
  Unable to fix IDE0052. No associated code fix found.
```

**Comment by jmarolf** [comment]
agree that violating analyzers should result in check returning non-zero

**Comment by bourquep** [comment]
@jmarolf Just to be clear: it _does_ return non-zero when violating analyzers, as long as it knows how to fix the violation.
