### ISSUE TITLE
Disabling formatting for selected folders

### ISSUE THREAD

**Issue by tomekpaszek** [dotnet/format#771]
Hi!
Following this [issue](https://github.com/dotnet/format/issues/8) I'm still wondering if there is a way to disable formatting for a given folder. The only way that comes to my mind right now is doing a pre-pass where I'd scan for those folders and pass them as `--exclude` parameter. This seems unnecessary as I'd simply like to configure that in `.editorconfig`.

**Comment by jmarolf** [comment]
I would expect a nested editorconfig that has different formatting settings would be supported. We should support formatting options per _file_ as you can do things like this in editorconfig:

```ini
[Program.cs]
dotnet_analyzer_diagnostic.severity = none
```

@tomekpaszek if this isn't working its a bug, can you provide a repro where a nested editorconfig is ignored so we can fix it? thanks!

**Comment by tomekpaszek** [comment]
What you've described indeed works but it's not what I'm asking for. 
I would like to have an option the tell the formatter "ignore this folder or file" (do not touch it) rather than "use default values when formatting" (it's what an empty `.editorconfig` would do).

Something like 
```
[Unformatted.cs]
dotnet_format_enable = false
```
would result in `Unformatted.cs` not being touched by the formatter.

**Comment by JoeRobich** [comment]
@tomekpaszek A workaround that you can use today is to flag the folders as containing only generated code.

```ini
[Unformatted.cs]
generated_code = true
```

**Comment by JoeRobich** [comment]
@tomekpaszek Also, I am curious what it is about these files that you would like to exclude them from formatting. It could be a use case that we have not considered.

**Comment by tomekpaszek** [comment]
> @tomekpaszek Also, I am curious what it is about these files that you would like to exclude them from formatting. It could be a use case that we have not considered.

I work at Unity and I'm investigating possibility of switching to `dotnet format` for our C# code. Our current tooling supports that kind of workflow. Currently, we use custom tooling for selecting files and uncrustify as the formatter. It's important that the solution would be fairly backwards compatible so the transition would be as smooth as possible. 

I don't know every case but codegen and some test code are just some examples.

**Comment by tomekpaszek** [comment]
> A workaround that you can use today is to flag the folders as containing only generated code.

Unfortunately I didn't manage to make it work. I've also tried with version `4.1.131201` as. well as the dev build `5.0.135301`

**Comment by JoeRobich** [comment]
@tomekpaszek Sorry I thought we got the `generated_code` support from Roslyn for free. Opened a PR to add support for this setting.

**Comment by parched** [comment]
`generated_code = true` doesn't work well because it triggers CS8669.

My specific use case is a 3rd party git submodule that I don't want to modify, so I can't just disable CS8669.
