### ISSUE TITLE
Disable dotnet-format for a section of the code via comments or preprocessor directives

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/format#782]
It would be nice to be able to turn off dotnet-format for a section of lines via line comments, similar to what clang-format offers: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code

This comes in handy, if you have unit tests that test C# code and the generator of said code is not Roslyn or does not understand .editorconfig.

Real world use-case: see the diff snippet in https://github.com/icsharpcode/ILSpy/issues/2128#issuecomment-682349215

**Comment by sharwell** [comment]
```
#pragma warning disable format

...

#pragma warning enable format
```

**Comment by siegfriedpammer** [comment]
Thank you for answering this. Kind of embarrassed I missed this.
