### ISSUE TITLE
Update "how to use" section to state it only works in a solution directory

### ISSUE THREAD

**Issue by koolraap** [dotnet/format#79]
For the dummies amongst us, it'd be useful if the How To Use section had something indicating that if you're not in a project folder dotnet-format doesn't get executed. I was trying all sorts of things to confirm it had installed correctly, but not in a project directory.

dotnet-format
dotnet tool list
dotnet tool format
dotnet tool run dotnet-format
dotnet tool run format
dotnet dotnet-format
dotnet format

cd \code\myproject
dotnet-format

Ahhhh! Definitely a PEBKAC issue, but still, maybe it'll help other the other PEBKACs out there if the doco is aimed at n00bs.

**Comment by jmarolf** [comment]
@JoeRobich don't we notify the user if we can't find a workspace?

@koolraap did `dotnet format` no have any output when you ran it in a folder without any projects or solutions?

**Comment by JoeRobich** [comment]
@jmarolf We do have an error message, but if dotnet format failed to execute, then it wouldn't have displayed.

@koolraap If dotnet-format was installed as a global tool, then your $PATH should have been updated so that you could run dotnet-format from any folder. Would it be possible for you to recreate your experience of installing dotnet format and running it outside the project folder so that we could get a copy of the console output? It would help us improve this experience for others.

**Comment by koolraap** [comment]
@JoeRobich @jmarolf thanks for the replies.

When I run the command in a new CMD window today I see the error message you mentioned:

    C:\>dotnet-format
    Could not find a MSBuild project file or solution file in 'C:\'. Specify which to use with the --workspace option.

I don't recall seeing that yesterday, but I'm not 100% certain. I uninstalled an reinstalled and i see the same error message:

    C:\Users\koolraap>dotnet tool install -g dotnet-format
    You can invoke the tool using the following command: dotnet-format
    Tool 'dotnet-format' (version '3.0.4') was successfully installed.

    C:\Users\koolraap>dotnet-format
      Could not find a MSBuild project file or solution file in 'C:\Users\goodwst'.
    Specify which to use with the --workspace option.

    C:\Users\koolraap>

So... either there's something weird about first install, or, let's be honest, the more likely scenario, I wasn't paying any attention to the output of the utility. Which is awesome, btw.

I'll close this issue, if I hear anything from my coworkers I'll reopen.

Thanks!
