### ISSUE TITLE
--fix-style or -s doesnt work.

### ISSUE THREAD

**Issue by KasifMS** [dotnet/format#803]
hello Team,  i am trying to run dotnet-format command with --fix-style option, but it says "unrecognized command"

i am using version : 3.3.111304.  i have also tried with latest version but it throws same error.  

Can you look into this please?

dotnet-format --check --verbosity diag -s
Unrecognized command or argument '-s'

Usage:
  dotnet-format [options]

Options:
  -f, --folder <FOLDER>           The folder to operate on. Cannot be used with the `--workspace` option.
  -w, --workspace <WORKSPACE>     The solution or project file to operate on. If a file is not specified, the command will search the current directory for one.
  -v, --verbosity <VERBOSITY>     Set the verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]
  --dry-run <DRY-RUN>             Format files, but do not save changes to disk.
  --check <CHECK>                 Terminates with a non-zero exit code if any files were formatted.
  --files, --include <INCLUDE>    A comma separated list of relative file or folder paths to include in formatting. All files are formatted if empty.
  --exclude <EXCLUDE>             A comma separated list of relative file or folder paths to exclude from formatting.
  --report <REPORT>               Accepts a file path, which if provided, will produce a json report in the given directory.
  --version                       Display version information

**Comment by JoeRobich** [comment]
@KasifMS Sorry we were updating the Readme while in development. I have restored the section for the 4.x builds - https://github.com/dotnet/format/blob/master/README.md#latest-release-v41131201

To get access to the --fix-style option, you will need to install a development build as outlined here - https://github.com/dotnet/format/blob/master/README.md#installing-development-builds

**Comment by KasifMS** [comment]
thanks.  it worked using dev build.
