### ISSUE TITLE
Formatting does not work with C# 9 Record types

### ISSUE THREAD

**Issue by BickelLukas** [dotnet/format#805]
I have the following record type
```cs
    public abstract record TypedId
    {
        public Guid Value { get; init; } = Guid.NewGuid();
    }
```

when I run `dotnet format --check` I get the following output:
```
TypedId.cs(8,1): Fix whitespace formatting
```

after formatting this is what the file looks like:
```cs
    public abstract record TypedId
    {
        public Guid Value { get; init; } = Guid.NewGuid();
}
```

**Comment by Felk** [comment]
I have a similar issue. This is my code, properly auto-formatted:
```cs
    public record MatchInfo(
        IImmutableList<Pokemon> TeamBlue,
        IImmutableList<Pokemon> TeamRed)
    {
        public string? Stage { get; init; }
        public string? FieldEffect { get; init; }
        public float Speed { get; init; } = 1f;
    }
```
dotnet format de-indents it incorrectly:
```cs
    public record MatchInfo(
        IImmutableList<Pokemon> TeamBlue,
        IImmutableList<Pokemon> TeamRed)
    {
        public string? Stage { get; init; }
    public string? FieldEffect { get; init; }
    public float Speed { get; init; } = 1f;
}
```

**Comment by nathanpovo** [comment]
What version of `dotnet format` are you using?

Using the development build (version `5.0.142902+8012f4ede1bb9a4e90ac01efd204b0f1ee428f10`), the record:

````csharp
public record Artist
{
    public Artist(string name, Uri url)
    {
        Name = name;
        Url = url;
    }

    public string Name { get; init; }
public Guid? Mbid { get; init; }
        public Uri Url { get; init; }
}
````

gets formatted correctly to:

````csharp
public record Artist
{
    public Artist(string name, Uri url)
    {
        Name = name;
        Url = url;
    }

    public string Name { get; init; }
    public Guid? Mbid { get; init; }
    public Uri Url { get; init; }
}
````

**Comment by Felk** [comment]
I was using `5.0.135301+b255ad16af715cae7bf2a80cc1db697742f46d96`
I just updated with this command:

    dotnet tool update -g dotnet-format --version 5.0.142902 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

and ran `dotnet format` again.

Both your and my example now get properly formatted, thank you!

I also successfully tested the newest version as of now, `5.0.152601`.

**Comment by BickelLukas** [comment]
Confirmed working with `5.0.142902+8012f4ede1bb9a4e90ac01efd204b0f1ee428f10`
