### ISSUE TITLE
check for CS1591

### ISSUE THREAD

**Issue by KasifMS** [dotnet/format#806]
hello Team, wanted to check on how can we enforce CS1591 warning as part of check.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591 

I am using dev build : 5.0.145903
thanks.

**Comment by JoeRobich** [comment]
In your .editorconfig set the severity of the CS1591 diagnostic to warning or error.

```ini
[*.{cs,vb}]
# CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'
dotnet_diagnostic.CS1591.severity = warning
```

When you run your check specify the same severity when passing the `--fix-style` option.

```
dotnet format --fix-whitespace --fix-style warn --check
```
