### ISSUE TITLE
--check option does not work

### ISSUE THREAD

**Issue by robinmanuelthiel** [dotnet/format#81]
The new `dotnet format --check` does not seem to work. I would assume that it only shows if the `.editorconfig` rules have been applied or not but does not touch my files.

#### 1. Create a new project

```bash
dotnet new console -n Test
cd Test
```

#### 2. Add .editorconfig

```bash
root = true

[*.cs]
csharp_new_line_before_open_brace = false
```

#### 3. Run check option

```bash
dotnet format --check
```

## Expected outcome

The `dotnet format --check` command fails with non-zero exit code, beacse `Program.cs` does not apply to the `csharp_new_line_before_open_brace = false` rule.

## Actual outcome

The `Program.cs` file gets reformatted and the dotnet format --check` command completes successfully.

**Comment by sharwell** [comment]
My understanding from the previous pull request is `--check` does not imply `--dry-run`, but they can be used together.

**Comment by robinmanuelthiel** [comment]
That would mean that

- There is no difference between `dotnet format` and `dotnet format --check`
- The only difference between  `dotnet format -- dry-run` and `dotnet format -- dry-run --check` is the status code

This looks very confusing to me. Just tried the same steps as above with dotnet format -- dry-run --check. Same result. It formats my document.

**Comment by JoeRobich** [comment]
Hi @robinmanuelthiel,

We can do better with the documentation around these flags.

The `--check` flag will set the a non-zero exit code if files were formatted.

```console
~\Source\repos\Test> dotnet format --check
  Formatting code files in workspace 'C:\Users\jorobich\Source\repos\Test\Test.csproj'.
  Formatting code files in project 'Test'.
  Formatted code file 'Program.cs'.
  Format complete.
~\Source\repos\Test> echo $LastExitCode
1
```

The `--dry-run` flag will run the formatter and print messages, but changes will not be saved to disk.

You can use these two together `dotnet format --dry-run --check` to get the behavior you would like. Where files are checked for formatting changes but not actually formatted.

**Comment by robinmanuelthiel** [comment]
Okay, just checked the last exit code and it indeed is `1`. I am working with a bunch of other formatters and linters and that was super unclear to me. I would have expected some sort of error message and console output!

Will send a PR!

**Comment by francisminu** [comment]
Hi,

I was trying the same command: dotnet format --dry-run --check, but though the file was not modified, the command executed successfully. This was the rule I had:
csharp_new_line_before_else = true
`if (i == 0)
            {
                Console.WriteLine("i is 0");
            }else
            {
                Console.WriteLine("i is not 0");
            }`

If I run just --check, it formats the page, when I run dotnet format --dry-run --check, nothing happens to the file and the errors are not reported as well.
Any help is appreciated.

Thanks!

**Comment by francisminu** [comment]
Hi,

I was trying the same command: dotnet format --dry-run --check, but though the file was not modified, the command executed successfully. This was the rule I had:
csharp_new_line_before_else = true
`if (i == 0)
            {
                Console.WriteLine("i is 0");
            }else
            {
                Console.WriteLine("i is not 0");
            }`

If I run just --check, it formats the page, when I run dotnet format --dry-run --check, nothing happens to the file and the errors are not reported as well.
Any help is appreciated.

Thanks!

**Comment by jmarolf** [comment]
@francisminu can you file a new issue and point us at the code you were running dotnet format against?

**Comment by francisminu** [comment]
Sure, will do right away.
