### ISSUE TITLE
dotnet-format failing GHActions

### ISSUE THREAD

**Issue by eddynaka** [dotnet/format#816]
Hi,

today I opened a pr normalizing the charset, end_of_line and insert_final_newline (.editorconfig):
```
charset = utf-8 
end_of_line = lf
insert_final_newline = true
```

Locally (windows 10), everything is passing fine.
On GH Actions, i'm receiving hundreds of errors: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1289/checks?check_run_id=1134982116

how can I find the real issue?

Thank you!

**Comment by jmarolf** [comment]
what are your git settings? I assume git is checking out the files with different line endings. See docs [here](https://docs.github.com/en/enterprise/2.15/user/articles/configuring-git-to-handle-line-endings) for what git behaviors you can specify

**Comment by eddynaka** [comment]
Hi @jmarolf , I just added the .gitattributes:
```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=lf

# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
*.c text
*.h text
*.cs text

# Declare files that will always have CRLF line endings on checkout.
*.sln text eol=lf

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary
```

Even with this, I'm still getting the same issue. Do I need to add all extensions?

**Comment by jmarolf** [comment]
I would expect this to be enough.

```ini
# Set the default behavior, in case people don't have core.autocrlf set.
* text=lf
``` 

I would also run 
```bash
git add --renormalize .
```

**Comment by eddynaka** [comment]
@jmarolf , I did exactly that. And yet, still failing: https://github.com/open-telemetry/opentelemetry-dotnet/runs/1135183709

**Comment by JoeRobich** [comment]
Not sure if it is the problem, but the [docs](https://docs.github.com/en/enterprise/2.22/user/github/using-git/configuring-git-to-handle-line-endings) show the setting as `* text eol=lf` instead of `* text=lf`

```
# Set the default behavior, in case people don't have core.autocrlf set.
* text eol=lf
```

**Comment by jmarolf** [comment]
@eddynaka did setting the git property fix this issue for you?

**Comment by eddynaka** [comment]
@jmarolf , to be sincere, the pipeline stopped to complain about that. 

We can close this :)

Thank you
