### ISSUE TITLE
[loc][query] Help with translation 

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/format#827]
String Resource ID | 0; "Running_0_analysis"
-- | --
Source String | Running {0} analysis.
Subtenant | vscode_extensions
Source Control Link |  
Filename | Resources.[lang].xlf
Question | What will the placeholder be replaced with?

**Comment by cristianosuzuki77** [comment]
https://github.com/dotnet/format/tree/master/src/xlf in any of these files.

**Comment by cristianosuzuki77** [comment]
VCQ 291641

**Comment by JoeRobich** [comment]
In this case the substituted string will be either the `Resources.Code_Style` or the `Resources.Analyzer_Reference` string.
