### ISSUE TITLE
[loc][query] Need assistance with previous translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/format#828]
We're reviewing the translations that may need update.

String Resource ID | 0; "Fix_final_newline"
-- | --
Source String | Fix final newline.
Subtenant | vscode_extensions
Source Control Link |  
Filename | xlf\Resources.[lang].xlf
Question | Does this mean "fix the final character in the new line"? Or just "Fix the new line"?

**Comment by JoeRobich** [comment]
Duplicate of #829

**Comment by cristianosuzuki77** [comment]
Apologies.
