### ISSUE TITLE
[loc][query] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/format#829]
We're reviewing the translations that may need update.

String Resource ID | 0; "Fix_final_newline"
-- | --
Source String | Fix final newline.
Subtenant | vscode_extensions
Source Control Link |  
Filename | xlf\Resources.[lang].xlf
Question | Does this mean "fix the final character in the new line"? Or just "Fix the new line"?

**Comment by cristianosuzuki77** [comment]
VCQ 291642

**Comment by JoeRobich** [comment]
@cristianosuzuki77 The .editorconfig option (`insert_final_newline`) that we emit this string for controls whether a file ends with a newline or not. It is emitted when it is both expected but not found and when it is found but not expected.

"Fix the final newline character in the file" would be a more descriptive version of this string.
