### ISSUE TITLE
dotnet format not formatting on macOS

### ISSUE THREAD

**Issue by markti** [dotnet/format#831]
I'm running macOS x and dotnet format stopped formatting C# code in one of my projects. github super-linter gets it but I can't get dotnet format to fix it locally. 

from /src when I run dotnet format I get this:
Warnings were encountered while loading the workspace. Set the verbosity option to the 'diagnostic' level to log warnings

When i run dotnet format -v diagnostic I get this:
The dotnet CLI version is '3.1.402'.
  Using MSBuild.exe located in '/usr/local/share/dotnet/sdk/3.1.402/'.

and a few of these:
 Found project reference without a matching metadata reference

".editorconfig" is located in /src folder along with the *.sln file

Any ideas?

**Comment by jmarolf** [comment]
> Found project reference without a matching metadata reference

This is the issue. If you install the pre-release version using this command

```bash
dotnet tool install -g dotnet-format --version 5.0.142902 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
```

and re-running with -v do you get the same error?

**Comment by ProximaB** [comment]
@jmarolf Hi, I have a qucik question. Wanted to try dotnet-format tool how it compares to gofmt and I couldn't make it format the files. Here's the output. Nothing happened to code. Really so basic stuff push me to ask that on github... 🤷🏻‍♂️
```bash
> dotnet-format CompanyName.MyMeetings.ArchTests.csproj -v diag

  The dotnet runtime version is '5.0.0'.
  The dotnet CLI version is '5.0.100'.
  Using MSBuild.exe located in '/usr/share/dotnet/sdk/5.0.100/'.
  Formatting code files in workspace '/home/---/modular-monolith-with-ddd/src/Tests/ArchTests/CompanyName.MyMeetings.ArchTests.csproj'.
  Loading workspace.
  Complete in 9166ms.
  Determining formattable files.
  Skipping referenced project 'CompanyName.MyMeetings.BuildingBlocks.Domain'.
  Skipping referenced project 'CompanyName.MyMeetings.BuildingBlocks.Application'.
  Skipping referenced project 'CompanyName.MyMeetings.BuildingBlocks.Infrastructure'.
  Skipping referenced project 'CompanyName.MyMeetings.BuildingBlocks.EventBus'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Administration.IntegrationEvents'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Administration.Domain'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Meetings.IntegrationEvents'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.UserAccess.IntegrationEvents'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Administration.Application'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Administration.Infrastructure'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Payments.IntegrationEvents'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Meetings.Domain'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Meetings.Application'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Meetings.Infrastructure'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Payments.Domain'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Payments.Application'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.Payments.Infrastructure'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.UserAccess.Domain'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.UserAccess.Application'.
  Skipping referenced project 'CompanyName.MyMeetings.Modules.UserAccess.Infrastructure'.
  Skipping referenced project 'CompanyName.MyMeetings.API'.
  Complete in 448ms.
  Running formatters.
  Complete in 415ms.
  **Formatted 0 of 6 files.**
  Format complete in 10034ms.
```

**Comment by JoeRobich** [comment]
@ProximaB Sorry you are having issues with dotnet-format. A note about formatting a project file instead of a solution file, when formatting a single project dotnet-format only formats the code files from the specified project. 

Are you using an .editorconfig for you codestyle configuration? dotnet-format does have defaults when an .editorconfig isn't present but they aren't as strict. It is entirely possible your code is already formatted in an acceptable manner. You could try introducing obviously bad formatting in one of the projects' files and running the tool again.

**Comment by ProximaB** [comment]
@JoeRobich Thanks, you are right. I added more strict config and now I saw the results. Surprisingly it doesn't fix empty lines in object initialization and curly bracket in the same line in default mode. I get it every team can specify their code style but in my opinion it should be strict as a default.

**Comment by JoeRobich** [comment]
@ProximaB We use the Roslyn formatter which intentionally doesn't format Object and Array initializers.  As for whether dotnet-format should have stricter defaults than the Roslyn formatter defaults, we have discussed providing a way to generate a strict .editorconfig in the current directory. So, this is definetly on our radar.

**Comment by justinmchase** [comment]
Still seeing this issue. On linux I get an error but on mac it doesn't even try. Thus I have errors in my CI which cannot be reproduced locally.
