### ISSUE TITLE
Upgrade from .NET Core 2.1 to 3.1

### ISSUE THREAD

**Issue by Styxxy** [dotnet/format#843]
The project is being targeted to .NET Core 2.1. It will be EOL by August 2021 (source: https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle ). Might consider to upgrade to .NET Core 3.1 as it is the next LTS version in line?

https://github.com/dotnet/format/blob/03a8fc0f0c4565b31a8a17154132bf5f748d6b4e/src/dotnet-format.csproj#L4

**Comment by JoeRobich** [comment]
@Styxxy We target .NET Core 2.1 specifically because it is still under support. We do specifiy in our .csproj that the tool run on the latest runtime installed. So, you should get all the associated performance benefits of having a more recent runtime.

**Comment by Styxxy** [comment]
Missed that comment. Thanks for the info!
