### ISSUE TITLE
[Feature Request] Detailed logging to include line number and code violation details

### ISSUE THREAD

**Issue by ctolkien** [dotnet/format#90]
I'd like to be able to run this tool on a codebase and have it give me a list of the files + associated line numbers and the rule violation, we'd use this information to plumb back into our CI reports.

At the moment all we know is that a particular file needed modifying, nothing more specific.

It looks like the changes are applied at a document level currently so I'm not sure if this level of fidelity is possible. Presumably as VS can offer it up however, then there must be a way.

**Comment by ctolkien** [comment]
Naive bunch of code  from `CodeFormatter.cs` after a document is formatted:

```csharp
//get the differences between the formatted document, and the original
var diffs = await formattedDocument.GetTextChangesAsync(document, cancellationToken);
foreach (var item in diffs)
{
    var sourceText = await document.GetTextAsync(cancellationToken);
    var fixedText = await document.GetTextAsync(cancellationToken);

    var linePositionSpan = sourceText.Lines.GetLinePositionSpan(item.Span);

    var sourceLine = sourceText.Lines[linePositionSpan.Start.Line];
    var destinationLine = fixedText.Lines[linePositionSpan.Start.Line];

    logger.Log("log details above");
}
```

I imagine in practice there is a bunch more considerations to take into account. For instance certain `TextChanges` can likely apply to multiple lines?

I've also no idea on the correct API's to use here, I was just digging about in intellisense.

Sample output (in this case, the displayed line was indented 4 spaces too many):


```
Formatting code files in project 'dotnet-format'.
  CodeFormatter.cs 192 "                        var diffs = await formattedDocument.GetTextChangesAsync(document, cancellationToken);". New Text: "                    var diffs = await formattedDocument.GetTextChangesAsync(document, cancellationToken);"
```

**Comment by jmarolf** [comment]
Well happily accept a PR for this

**Comment by feliwir** [comment]
Any work being done on this already?

**Comment by ctolkien** [comment]
@feliwir  - I'm not working on this, got a newborn 👶 !

**Comment by JoeRobich** [comment]
These details now get logged during `--dry-run`s. You can try this out with the latest build from MyGet. 
```
dotnet tool install -g dotnet-format --version 3.1.36303 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```
