### ISSUE TITLE
Log the potential .editorconfig files for each project

### ISSUE THREAD

**Issue by asears** [dotnet/format#937]
Is there a way that we can increase verbosity of the logs to include the resolution method for which file path was selected for .editorconfig (in the case of repo-based, parent folder and project-based) and what styles are being applied?

I do not see any diagnostic messages in following file:
https://github.com/dotnet/format/blob/230d3cc8ee5fd76e0f4499b9edc4cfea1ff8bcbb/src/Utilities/EditorConfigFinder.cs

**Comment by JoeRobich** [comment]
@asears The `EditorConfigFinder` simply determines a set of potential .editorconfig files that *might* apply to the code within a Project when using the `--folder` option. When working against a .csproj or .sln file the potential .editorconfig files are determined by the SDK.

The work of parsing the .editorconfig files then determining which options apply to individual code files belongs to the Roslyn compiler. See https://github.com/dotnet/roslyn/blob/7194369da1ecb91f81f4607841f2ac321d6a7f21/src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs#L188

If all you need is a list of potential .editorconfig files for the project being processed, we could add diagnostic logging to print those out. If you are looking for logging of why individual options are applied to a code file, that will need to be a Roslyn enhancement request.

**Comment by asears** [comment]
Thanks!  I think it would be a useful feature to add the list of potential editorconfig files being processed to the diagnostic logs, if that's something which can be presented by dotnet-format. Unclear if MS build / dotnet build will give this to us.

It's very odd that it's traversing all the way to the root of the drive, though I get the intent was to be at the root of the repo.  It would probably require some knowledge of the folder structure being a repo to determine the repo root rather than just going to the drive root.

**Comment by JoeRobich** [comment]
> It's very odd that it's traversing all the way to the root of the drive, though I get the intent was to be at the root of the repo. It would probably require some knowledge of the folder structure being a repo to determine the repo root rather than just going to the drive root.

@asears According to the .editorconfig spec (https://editorconfig.org, *"When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory."*.  It is fairly cheap to locate these potential .editorconfig files upfront. When determining the actual options to apply, the presense of the `root = true` option limits the search through these potential configuration files.

I'll update the issue title to match the proposal and mark this as a feature request.

Proposal:

After opening the workspace to be formatted, loop through the projects and log the applied AnalyzerConfigDocument paths as debug messages.
