### ISSUE TITLE
Format without workspace

### ISSUE THREAD

**Issue by laktak** [dotnet/format#943]
Would it be possible to format a single file without having to specify a workspace?

For example I'd like to run `dotnet-format` from vim but vim does not use csproj files.

**Comment by jmarolf** [comment]
If the set of things you want to format doesn't require semantic knowledge (for example using Int32 over int) then yes you can just format a single file with `--include`

**Comment by laktak** [comment]
I can't get this to work. Do I need a later version?

```
$ dotnet-format --version
4.1.131201+82a5527cd93d66bffc885c0bb901499f5981db35

$ dotnet-format --include foobar.cs
Could not find a MSBuild project file or solution file in '/home/user/foo/bar'. Specify which to use with the --workspace option.
```

**Comment by JoeRobich** [comment]
@laktak Currently the `--folder` option isn't implied by `--include`, so it will need to be specied as well. `dotnet-format -f --include foobar.cs`

**Comment by laktak** [comment]
Thank you, that works!

Feedback: `--help` says:

>   <project>    The solution or project file to operate on. If a file is not specified, the command will search the current directory for one.

This implied to me that you need a project file.
