### ISSUE TITLE
Expressions of the form `switch {` cause dotnet-format to fail

### ISSUE THREAD

**Issue by mateoatr** [dotnet/format#948]
Whenever there's a switch expression with a { in the same line (`var switch {`), dotnet-format reports whitespace formatting errors. This makes it hard to understand what's wrong. For an example, see here: https://dev.azure.com/dnceng/public/_build/results?buildId=971006&view=logs&j=ed7ee28b-73cd-526d-4740-b3f2e2c1c6bb&t=e71a6653-5b93-50ae-6545-9f859da4990d&l=365.

**Comment by JoeRobich** [comment]
Hi @mateoatr, Switch expressions should be supported in the 5.x builds. We are working toward a public release but nightlies can be [pulled from Azure Artifacts](https://github.com/dotnet/format#installing-development-builds). Roslyn support for switch expressions was tracked by https://github.com/dotnet/roslyn/issues/36913

**Comment by JoeRobich** [comment]
Closing as a 5.0 build is now available on NuGet.org
