### ISSUE TITLE
Should support running on slnf files

### ISSUE THREAD

**Issue by Pilchie** [dotnet/format#954]
Most people in aspnetcore work on a subset of the entire solution, which we track using slnf files. It would be great if we could specify a .slnf file as the scope of something to run dotnet format on.

**Comment by jmarolf** [comment]
my assumption is that this requires work in MSBuildWorkspace to support loading slnf files.

**Comment by JoeRobich** [comment]
> my assumption is that this requires work in MSBuildWorkspace to support loading slnf files.

Currently MSBuildWorkspace still loads all projects from the solution. We will need to update it to filter appropriately.

**Comment by JoeRobich** [comment]
We can move forward on this issue once the changes to Roslyn's MSBuildWorkspace in https://github.com/dotnet/roslyn/pull/51782 are merged.

**Comment by Pilchie** [comment]
Thanks!
