### ISSUE TITLE
StdErr support

### ISSUE THREAD

**Issue by sungam3r** [dotnet/format#955]
Please add command-line swith to output warnings and errors to `stderr`. Now I see that `SimpleConsoleLogger` always writes to `_console.Out`

**Comment by sungam3r** [comment]
@JoeRobich Thanks! Is this fix already available on nuget?

**Comment by JoeRobich** [comment]
> Is this fix already available on nuget?

Not yet, but it is available from our Azure Artifact feed. You can follow these instructions to install https://github.com/dotnet/format#installing-development-builds

**Comment by sungam3r** [comment]
OK. I see you changed docs to point to `6.0.*` from `5.0.*`. Thanks.

**Comment by sungam3r** [comment]
It works 👍

**Comment by Frost84** [comment]
Thanks a lot!
