### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by sungam3r** [dotnet/format#957]
See explanation in https://github.com/DotNetAnalyzers/IDisposableAnalyzers/issues/259

How to deal with that error ?

**Comment by JoeRobich** [comment]
@sungam3r Thanks for opening this issue. I added a test for this analyzer package. It had no issue loading on its own, so the issue may be that multiple versions of the Gu.Roslyn.Extensions are being loaded and we are not isolating these dependencies (which is a bug filed under https://github.com/dotnet/format/issues/734).

I also noticed that the FixAllProviders were failing from this package and implemented a fix to support them. See https://github.com/dotnet/format/pull/958.

**Comment by JoeRobich** [comment]
After updating the test to load more of the Analyzers from your project, the true issue was revealed. We resolve dependencies when the Analyzer and CodeFix types are realized. However, we were only tracking the last analyzer assembly paths as a search path. In this case the Gu.Roslyn.Extensions assembly isn't present in that final path causing the FileNotFoundException.

**Comment by JoeRobich** [comment]
Going to take this a step further and simply isolate each analyzer into its own assemblyloadcontext.

**Comment by sungam3r** [comment]
I'm glad to hear that.

**Comment by sungam3r** [comment]
How can I get a new version to try the fix?

**Comment by JoeRobich** [comment]
@sungam3r Typically we have a nightly build, but I kicked it off special for these fixes. You should be able to uninstall and reinstall the dotnet-format tool to get the latest version.

**Comment by sungam3r** [comment]
Thank you. It works.
