### ISSUE TITLE
Latest format tool v5.0.211103 does not work with .NET Core 2.1.25

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/format#986]
Hi @JoeRobich

When I installed the latest format tool v5.0.211103, and my machine only has .NET Core 2.1.25 installed, `dotnet format` does not work.

It looks like caused by the following change, when I removed `-rc1` from the config file, it works fine.
[https://github.com/dotnet/format/blob/eadde172822e75922a68332d1037972f1fcec791/src/dotnet-format.csproj#L19](https://github.com/dotnet/format/blob/eadde172822e75922a68332d1037972f1fcec791/src/dotnet-format.csproj#L19)

![issue](https://user-images.githubusercontent.com/49379637/108471036-cdb13a80-72c5-11eb-9437-f63a1e734ab3.png)

**Comment by JoeRobich** [comment]
@jiangzeng01 Thanks for logging this issue.

@wli3 I guess this is because the 2.1 dotnet doesn't understand the rollforward. Do we have options here?

**Comment by jmarolf** [comment]
@wli3 it appeasrs that we cann specify roll-forward behavior to both released and previews versions per this doc [here](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md) is that only applicable to newer runtimes?

**Comment by wli3** [comment]
roll forward should be a simple string match. I think 2.1.0-rc1 is not a substring of 2.1.0?

@vitek-karas could you explain the detail logic of rolling forward?

**Comment by vitek-karas** [comment]
2.1 actually did understand roll forward (the setting was called `rollForwardOnNoCandidateFx`), but it worked somewhat weirdly for pre-release versions: https://github.com/dotnet/runtime/blob/master/docs/design/features/framework-version-resolution.md#pre-release
The short version - pre-release version would never roll forward to release version.

The workaround would be to install 3.0+ on the machine. The roll forward logic is in `hostfxr.dll` which is global and always the highest version is used. The 3.0 of hostfxr should enable roll-forward from pre-release to release: https://github.com/dotnet/runtime/blob/master/docs/design/features/framework-version-resolution.md#pre-release-will-roll-forward.

Why do we have an unsupported pre-release version in the `.runtimeconfig.json` of the latest version of our tool?

**Comment by jmarolf** [comment]
> Why do we have an unsupported pre-release version in the .runtimeconfig.json of the latest version of our tool?

goal is to be able to run on release and pre-release runtimes from 2.1 onward. What is the best way to achieve that?

**Comment by jiangzeng01** [comment]
Thanks for fixing!
